src/projects/FeatureSelector/DefaultFeatureForm.jsx, src/projects/detail/components/EditProjectForm.jsx
-- Fixed
@parthshah can you please review the change? I am not sure if this is the best way to fix this issue. Basically, issue is occurring because the `project.details.appDefinition` is not set if user hasn't saved the project with at least one question answered.
=> AS#181122346682552, Project Details/Feature Picker: selected features are not being saved

src/components/MessageList/MessageList.jsx, src/components/MessageList/MessagingEmptyState.jsx, src/components/MessageList/MessagingEmptyState.scss, src/components/Panel/Panel.scss, src/projects/detail/Messages.jsx, src/projects/detail/Messages.scss, src/projects/detail/containers/MessagesContainer.js
-- Added empty states for MessageList and right panel of the MessageContainer
@parthshah @fnisen fyi
@parthshah I am having an issue with loading spinner HOC. It seems it renders the target component even before the isLoading is set to false. This is causing empty states to be visible while we are fetching the feeds. Can you please help me out here?
=> Github issue #149 Messaging: empty state for messaging tab

src/projects/detail/components/FeatureSelector/CustomFeatureForm.jsx
-- Fixed by putting maxlength on the input element. However, if we need to inform user about the limit we might want to use validation error rather.
=> Github issue #296 max length validation must be present on Custom Feature title otherwise its showing aligement issue

src/components/FileList/FileListItem.jsx
-- Fixed situation where user can not save new file name after emptying the file name field.
=> Github issue #267 throwing error on saving blank name of uploaded file

src/components/TeamManagement/OwnerModal.jsx, src/components/TeamManagement/TeamManagement.scss
-- Fixed copy and missing name in the modal
=> Github issue #492 [Team Management] Buttons are not center aligned in assign owner modal

src/projects/detail/Messages.scss, src/projects/detail/containers/MessagesContainer.js
-- Wrapped message container into full height container. Also had to remove the sticky behaviour to not have overflow issue when page is scrolled to the bottom. And, I guess, in after scrolls bar we don't need sticky behaviour anyway.
@vic-appirio Please let me know if you think we have non javascript solution for this.
=> Github issue #395 When user select the "Messages" from the list; posts related to that Message won't see

src/components/TopBar/TopBar.jsx
-- Fixed. Now it reloads the page even if user is already on project listing page.
=> Github issue #287 after applying search if click on Connect logo, should lands user to project listing page

src/components/MessageList/MessageList.jsx, src/projects/detail/containers/MessagesContainer.js
-- Now the list will be scrolled to the specific discussion in the left panel. This is working fine for Chrome and Firefox. For Safari, right now the left panel is not having the scroll bar (Separate issue is logged for that).
=> Github issue #517 Discourse email to topic link: scroll users to the correct topic on Discussions page

src/components/TeamManagement/AddTeamMember.jsx, src/components/TeamManagement/AutoCompleteInput.jsx
-- Applied fix from winner of the challenge. This fix has least intrusive changes with only two files being changed and only 3 lines of addition overall. Other change which I committed in separate branch ([feature/add_team_member_scroll](https://github.com/appirio-tech/connect-app/commit/f83c2aedd173701c8f1381092890d7e3afb28523)) works fine but has changes in more 6-7 files and requires functional component to be stateful. So, we are going to accept this fix as final solution.
=> Github issue #526 Add Team Member || Modal is not visible after clicking on Add button

src/projects/actions/projectTopics.js
-- Found critical issue when reviewing the code the mentioned issue. It was causing wrong posts to be shown under a topic.
=> Github issue #527, Discussions: Discussion thread not showing all posts

src/projects/detail/components/EditProjectForm.jsx, src/projects/detail/containers/SpecificationContainer.jsx
Github issue #541 Project Details: notify user when they are leaving Specification tab without saving changes
Github issue #542 Project Specifications || Save buttons should be disabled when form is pristine
-- Got them fixed by community. Winner: utkarshkukreti
=> Project specification form state issues

src/projects/list/components/Projects/Projects.jsx
-- Fixed the case where scroll position was being maintained even in case of user moving between different pages of the project listing.
=> Github issue #552, Project listing: return user to previous spot in listing after back from project

src/config/constants.js
-- Fixed. Reason was the missing # in URL. # is required for angular routes.
=> Github issue #566, Connect Login/Logout redirect not working correctly in Safari

src/components/FooterV2/FooterV2.jsx
Updating footer Help link to point to Help Center FAQ instead of general help page
=> Updating footer Help link

src/projects/detail/containers/TeamManagementContainer.jsx
-- Aliased administrator roles to act like as connect manager
@parthshah fyi, please let me know if we need to make any other change to achieve the functionality. I have tested these changes on my local with vbailey user (I have added `administrator` role to the user apart from `copilot` role which she already had) and now I am able to see all projects and able to join them as Manager.
cc: @fnisen
=> Github issue #579, General: allow "admin" role to have same rights as "manager" role

src/projects/reducers/projectTopics.js
-- Fixed. We were missing sorting the posts when loading more posts for a feed
@parthshah fyi
=> Github issue#587, Comments Sort order within a topic is incorrect

src/components/Grid/GridView.scss, src/components/Grid/PaginationBar.jsx, src/projects/list/components/Projects/Projects.jsx
-- Fixed issue for the case when incorrect results were being shown when user hits browser back button after navigating the list pages via paginator
-- CSS fix as suggested in Github
-- Applied light theme for the tooltip
=> Github issue #372, [Pagination] - keep fixed pagination option displaying 5 pages.

src/projects/detail/components/SpecQuestions.jsx
Related issue: #639 
@gondzo I've submitted a PR on the `react-components` repo.
To test changes on this repo you can simple modify the package.json to fetch react-components from `ThomasKranitsas/react-components.git#update-tileradiogroup`
Note that the disabled/enabled options are updated after you click the `Save changes` button. I discuss this with @fnisen on slack and we decided to change the functionality to update disabled/enabled options when adding/removing screens after we merge both this PR & https://github.com/appirio-tech/connect-app/pull/666 otherwise we'll get conflicts.
Ref: https://github.com/appirio-tech/react-components/pull/126
=> Fix screen limit after defining some screens

src/projects/detail/components/EditProjectForm.jsx, src/projects/detail/components/SpecQuestions.jsx, src/projects/detail/components/SpecScreenQuestions.jsx, src/projects/detail/components/SpecSection.jsx
Related issue: #628 
To test it you have to either merge this https://github.com/appirio-tech/react-components/pull/124 PR in the `react-components` repo or modify the package.json so the `appirio-tech-react-components` is fetched from `ThomasKranitsas/react-components.git#autoresize-textarea`
=> Make all textareas in project specification autoresizable

src/config/projectQuestions/avd.v1.0.js, src/projects/detail/components/SpecSection.jsx
Related issue: #680 
This is a generic solution (not just for the screens section).
Now if you add the `hideTitle: true` to any `subSections` in `/src/config/projectQuestions/avd.v1.0.js` the heading won't be rendered.
=> Remove the 'screens' heading from Screens section

src/components/ProjectStatus/ProjectStatusChangeConfirmation.jsx, src/components/ProjectType/ProjectType.jsx, src/config/projectWizard/index.js, src/projects/detail/components/SpecQuestions.jsx, src/projects/detail/components/SpecSection.jsx, src/projects/detail/components/VisualDesignProjectEstimateSection.jsx
Issue #640
The issue was that the `*` was only rendered on the title of each `required` subSection.
So when a subSection is `type: 'questions'` then the `*` is only rendered on the subSection title and not on each question title.
=> Fix missing * form manatory fields of type 'questions'

src/components/TextInput/TextInput.jsx, src/projects/create/components/WizardHeader.jsx
=> Fixed #696 Project Name should be focused immediately after rendering the project creation form

src/projects/detail/components/EditProjectForm.jsx
-- Fired PROJECT_DIRTY action for every change event fired by the form. Earlier it was firing the PROJECT_DIRTY action only if the form has actually changed its model from the original value.
=> Github issue#691, Refresh Project Estimate component on change of number of screens

src/projects/create/components/ProjectWizard.jsx
Github issue#1102, Process/add ref code from deep link
Github issue#1037, Project spec information is not saved when changing project types
=> Reading refcode from URL

src/config/projectWizard/index.js, src/projects/create/components/ProjectWizard.jsx
— copying goal and users fields as well when user changes the product type.
— it now validates, before copying, if the target product template contains the fields being copied.
=> Github issue#1037, Project spec information is not saved when changing project types

src/projects/detail/components/SidebarNav.jsx, src/projects/detail/components/SidebarNav.scss
— Not rendering the number for single section template
— Fixed padding of sub sections of the section in such cases
=> Github issue#1125, Do not show section number when there is only one section

src/components/TopBar/Filters.js, src/config/projectWizard/index.js
— Fixed. Made the list of the project types to be dynamic. It was hard coded earlier because earlier we were showing different label in filters than what we have in the projectWizard/index.js
=> Github issue#1212, Filter project types in admin view

src/components/Footer/Footer.jsx, src/components/FooterV2/FooterV2.jsx
Remove "Help" from connect footer.
Rename "Contact" to "Contact us"
=> Footer updates fix #1322

npm-shrinkwrap.json, src/components/FileList/FileList.jsx, src/config/projectQuestions/app_dev.v1.0.js, src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/generic_chatbot.v1.0.js, src/config/projectQuestions/ibm_chatbot.v1.0.js, src/config/projectQuestions/mobility_testing.v1.0.js, src/config/projectQuestions/real_world_testing.v1.0.js, src/config/projectQuestions/visual_design.v1.0.js, src/config/projectQuestions/website.v1.0.js, src/config/projectQuestions/wireframes.v1.0.js
— After this issue is fixed in react-components repo, updated project templates in connect app to get rid of unnecessary validationError field even though we have provided validationErrors object.
It does not add any feature or fixes any bug in connect app. Rather it adapts the uses of form component validations from react-components repo which got an issue about validation error, with custom validations, fixed via https://github.com/appirio-tech/react-components/issues/273.
**Verification:** After merging it in dev, to verify that it fixed the issue and didn't create any regression, we should be able to see validation error 'Please provide a description' when user clears out the description field after entering some value first.
=> Github issue#272, Validation error for custom validation is not working

src/routes/settings/routes/notifications/components/NotificationSettingsForm.jsx, src/routes/settings/routes/notifications/components/NotificationSettingsForm.scss
Issue #1465 - hide email settings column and replace it with a link to email settings
Here is how it looks
=> Issue #1465 - hide email settings column and replace it with a link

src/components/ActionCard/Comment.jsx, src/projects/detail/ProjectDetail.jsx
Issue #1507 - Clicking on project post notification doesn't enable the Dashboard section
Project wasn’t switched at all when we click links to another project from the project page.
=> Issue #1507 - Clicking on project post notification doesn't enable the Dashboard section

src/components/ProjectStatus/ProjectStatus.scss, src/components/ProjectStatus/editableProjectStatus.js
Issue #1497 - Dropdown menu doesn't take viewport bounds into consideration.
Quick solution: always dropdown “upside” if click in the bottom half of the window.
=> Issue #1497 - Dropdown menu doesn't take viewport bounds into consideration.

config/constants/dev.js, src/routes/notifications/constants/notifications.js, src/routes/notifications/helpers/notifications.js
Issue #1554 - User in notifications are listed with @handle instead of their name
This PR works together with [PR](https://github.com/topcoder-platform/tc-notifications/pull/10) to `tc-notifications` but DOESN'T require it. 
Changes keep backward compatibility so connect-app suppose to work with current version of `tc-notifications` also.
=> Issue #1554 - User in notifications are listed with @handle instead of their name

src/components/TeamManagement/TeamManagement.scss
In TeamManagement.scss, the style ‘.modal-inline-form button’ had it's margin-left unnecessarily set to $base-unit*2 (10px). The inherited value of 5px was all that was needed…  This along with the button’s inherited left and right padding of 25px created an extra 15px of width overall, causing the container to appear wider than intended. Simply removing this margin-left style doesn’t suffice, since the button’s left and right padding needed to be decreased to 20px each so to correctly reduce the container width by 10px total, as well as to ensure the inner text ‘Add’ is centered. The add team members container now behaves as intended with the correct width.
=> issue-1616

src/components/TopBar/ProjectsToolBar.js
onTermChange is required by the SearchBar component from appirio-tech-react-components, and it will be called in SearchBar's onChange function. So handleTermChange is needed here unless we modify SearchBar component. 
callback is necessary to remove the loading spinning logo (which is called by the Search to change its state and hide the loading logo). 
The simplest way the avoid unnecessary action call is to remove the line of calling  this.props.projectSuggestions and keep the callback function to keep the Search Bar work. 
#1603
=> #1603 Search box performance issue

src/components/TopBar/ProjectsToolBar.scss
=> fix #1774: Search bar showing 2 cross buttons on edge browser

src/components/ProjectStatus/ProjectStatus.scss, src/components/ProjectStatus/editableProjectStatus.js
=> fix #1804: select a status change without closing the previous modal

src/components/Maintenance/Maintenance.jsx, src/routes/settings/routes.jsx
Right now maintenance page breaks for me due to missing react import in Maintenance.jsx and /error and /404 error pages are not visible due to screwed up routing in src/routing/settings page. My this pull request fixes both issues to make these pages working. Please give feedback.
=> Fixed code to make maintenance and error pages visible

src/components/Layout/Layout.js, src/projects/reducers/project.js
Now it should not show maintenance page for 403 or any custom status returned by the API, it should be shown only if the API endpoint does not exist.
=> Handling non 404 more appropriately

src/components/Feed/FeedComments.jsx
In favour of #2128 
- Load the project locally `npm start` 
- Login with `pshah_manager/topcoder123`
- Navigate to [http://localhost:3000/projects/6446](http://localhost:3000/projects/6446)
- Click on **Wireframes**
- Observe the position of `load earlier posts` button
=> Reposition load more button under time stamp #2128

src/components/ProjectInfo/ProjectInfo.jsx
The fix is easy, clear and robust, safe for deploy.
The issue was with the package [react-text-truncate](https://github.com/ShinyChang/React-Text-Truncate) that we use to truncate too long project description on the dashboard with `read more` link.
For mobile resolutions, the truncate maximum lines has been set to `Infinity` which caused in some circumstances the infinite loop in the plugin, see https://github.com/ShinyChang/React-Text-Truncate/blob/master/src/TextTruncate.js#L133
I put `1000` as trancate maximum lines, feels like this is enogh for project descriptions to be shown fully without trancations.
NOTE, that even big finite values like `1 000 000` cause browser to freeze.
=> fix freezing project dashboard page on mobile resolutions

src/components/Feed/FeedComments.jsx
This PR solves #1994
- Load the project locally `npm start` 
- Login with `pshah_manager/topcoder123`
- Navigate to [http://localhost:3000/projects/4963](http://localhost:3000/projects/4963)
- post a comment and reload the page
- Leave the project
- post a comment and reload the page
- It does not crash like before now.
=> Fix created post by non-member of the project breaks posts feed

src/projects/create/components/ProjectBasicDetailsForm.js, src/projects/detail/components/SpecSection.jsx
Hotfix which hides `hiddenOnCreate` questions during project creation wizard. For example, it hides file attachments. 
This is done by cherry-picking a commit from [dashboard-improvements](https://github.com/appirio-tech/connect-app/commits/feature/dashboard-improvements) branch.
=> Hotfix/hidden on creation to PROD

src/api/timelines.js, src/projects/actions/project.js
**Description** #2227 
Right now we are calling milestone's POST call multiple times to create milestones for a timeline. Now we have backend supported with implicit creation of milestone when calling POST for milestone with templatedId param passed, so this single call will create timeline and all the associated milestone using value of templatedId.
=> Issue #2227: Remove individual calls for creating milestones for a timeline

src/projects/actions/project.js
Right now, when a POST call for timeline and milestone is made the hours are also getting persisted along with date, need to remove hours from the timestamp getting persisted.
- Remove hours from timeline milestone requests
=> Issue #2230: Don't include hours when persisting date fields for timeline and milestones

src/projects/detail/components/SpecSection.jsx
It is setting the category incorrectly, which is causing the files to be not visible after project has been migrated to v3.
=> Hotfix for fixing attachments for v2 projects

src/components/Feed/FeedComments.jsx
issue #2366 - Root post should not have delete post option
Done, so Delete post is not shown for root post.
I can make it look like disabled instead, but when user will click it, the dropdown will be closed anyway even it look disabled. I cannot prevent closing in current implementation as it uses `<DropdownItem>` component from `appirio-tech-react-components` which doesn't let us prevent closing `<Dropdown>` when we click it.
Also, styling of the disabled option would be done not the best and slightly hacky way because of the limitations of `<DropdownItem>` component from `appirio-tech-react-components`.
Please, let me know if you still want to keep it with disabled styles, even though when user will click it dropdown will be closed (delete action wouldn't be called, just closed …
=> issue #2366 - Root post should not have delete post option

package.json, src/components/Home/Home.jsx, src/config/constants.js, src/projects/create/components/FillProjectDetails.scss, src/projects/create/components/IncompleteProjectConfirmation.js, src/projects/create/components/ProjectSubmitted.jsx, src/projects/create/components/ProjectSubmitted.scss, src/projects/create/components/ProjectWizard.jsx, src/projects/create/components/ProjectWizard.scss, src/projects/create/components/SelectProjectType.jsx, src/projects/create/components/SelectProjectType.scss, src/projects/create/components/_layout.scss, src/projects/create/containers/CreateContainer.jsx, src/projects/create/containers/CreateContainer.scss
1. Save the new user info (Business Phone, Title, Company Name, and Company Size) - we’ll need call the new traits API to add the business information Postman here: https://www.getpostman.com/collections/9d74c856e4a79510af01 This has to be done after the registration calls because it uses the TC username
2. Return back to connect when clicking the select your solution button. redirect to  CONNECT_URL/new-project route
3. In connect app remove unauthenticated project creation flow from routes, so that it now always requires users to login before creating project
4. In connect-app update CreateContainer and its child components to include the new left and right panel in the project creation wizard
5. In connect app add new step in the project wizard for showing the `Project Submitted` step …
=> finish left steps in registration/login flow

src/routes/notifications/helpers/notifications.js
I propose to log warning instead of throwing an exception when a rule for notification is not found.
Otherwise, notification functionality just got broken.
I think it's better to merge this PR without waiting for the second part of issue #2541 so notifications are not broken in `dev` branch.
=> issue #2541 -  log warning using console.warn() instead of throwing an exception when a rule for notification is not found

src/projects/detail/containers/ProjectInfoContainer.js
issue #2465 - fix displaying discussions on the sidebar for old projects which don't have phases
Currently, old projects, which don't have phases cannot load properly.
=> issue #2465 - fix displaying discussions on the sidebar for old projects which don't have phases

src/routes/settings/routes/notifications/components/NotificationSettingsForm.jsx
Additional fixes for issue #2522
@vikasrohit 
> btw, it seems we can not save `every 10 minutes` setting in notification settings now
I think the issue was not connected with `every 10 minutes` but with value for `bundlePeriod`, as a server doesn't accept `null`. Also, I've noticed not correct behaviour of default value for email settings of messaging notifications.
- fixed setting `bundlePeriod` to `off` by using an empty string `''` instead of `null`
- fixed default value for messaging notifications by email:
- only for notifications related to messagin, if settings is not defined, then by default email notifications are `off` (bundlePeriod is '')
- for the rest of notifications, default value is `daily`
=> issue #2522 - additional fixes

src/projects/detail/components/EditProjectForm/EditProjectForm.scss
=> Github issue#2707, Slider dots are off the slide rail in project edit scope form

src/projects/detail/components/timeline/Timeline/Timeline.jsx
- Proper fix, for #2718 , after identifying the root cause. Previous fix is also good to have for future unhandled situations.
RCA: the issue is reproducible when there is at least one active phase in the project and there is a notification for timeline adjustment for one of the phases. Error appears when app tries to auto expand the active phase cards on the dashboard. And reason for the issue not being reproducible as Admin or Manager role is that we don't auto expand the phase card for any non customer user.
=> Github issue#2718, Unable to load messages for customers

src/components/TeamManagement/TopcoderManagementDialog.js
— Should be fixed. Root cause is that some how a customer role user is being rendered in the topcoder team dialog. However, this fix should allow graceful failing in such situations as well.
=> Github issue#2921, Cannot read property 'title' of undefined

src/config/form-schemas/form-v1.json, src/config/form-schemas/form-v2.json
Form JSON schemas which cover two types of form templates old ones and the new one with the support of wizard.
I suggest keeping them inside Connect App as later we can use them in the JSON editor to validate templates during editing.
=> Form JSON Schemas

src/helpers/wizardHelper.js, src/projects/create/components/ProjectBasicDetailsForm.js, src/projects/detail/components/EditProjectForm/EditProjectForm.jsx
> can we by pass the specific deliverable addon section when there is no addon for that particular deliverable e.g. as of now Deployment does not have any add on, we want to skip directly to the final summary screen when user selects only the Deployment as deliverable and answers all required question i.e. we want to skip the intermediate summary screen and the the empty screen which asks for selecting addons.
This is done. At the moment the solution uses section IDs to detect intermediate section and add-ons section:
```
section.id === 'summary-intermediate'
section.id === 'add-ons'
```
This binds the logic to the particular template. But anyway it looks like there is no other way to describe this logic or we should introduce some additional properties to define these sections. 
I think …
=> skip empty addons

src/components/Feed/FeedComments.jsx
- Moving Add Post text box above the comments to match with the new reversed order of posts
fyi @maxceem @RishiRajSahu
=> Github issue#2934, Newest message displays at the top of thread

src/projects/detail/components/SpecQuestions.jsx
Need to merge only if we need vertical layout for new kubik forms.
=> Enabling layout property for radio group component so that we can have vertical layout for radio group

src/components/RichTextArea/LinkPlugin/EditLinkPopover/EditLinkPopover.jsx
Fix issue mentioned in https://github.com/appirio-tech/connect-app/issues/2937#issuecomment-492094038
=> fix draftjs link editor opening autopopover without title

src/components/RichTextArea/LinkPlugin/LinkPlugin.js, src/components/RichTextArea/LinkPlugin/utils/handlePaste.js
This PR fixes this issue in DraftJs editor:
If we paste text link "test http://some-link.com test" the link inside such text would stay as a text.
- all links inside text should become links
- show the small popup for adding a title to the latest link in the text
=> [HOTFIX][PROD] DraftJs Link Fix

src/config/constants.js
— Fixed, as per discussion in team call, now we would redirect all users to `All Projects` by default.
=> Github issue#3090, Direct Invited Just-Registered Users to All Projects Dashboard

src/projects/create/components/ProjectEstimation.js, src/projects/create/components/ProjectEstimation.scss, src/projects/detail/ProjectDetail.jsx, src/projects/detail/components/SpecQuestions.jsx, src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/ProjectPlanContainer.jsx
Showing project estimation component at the top of the page. It's the first part of the issue https://github.com/appirio-tech/connect-app/issues/2967
It's shown on both tabs: **Dashboard** and **Project Plan**
For testings:
- Example project which has estimation calculated https://connect.topcoder-dev.com/projects/8103
- Example project which CANNOT calculate estimation https://connect.topcoder-dev.com/projects/8113
- Example of old `v2` project which doesn't have an estimation component https://connect.topcoder-dev.com/projects/5000
This is a winner submission from challenge [30092039 - Topcoder Connect - Show project estimation](https://www.topcoder.com/challenges/30092039)
=> Project estimation component

src/projects/detail/components/ProjectStage.jsx, src/projects/detail/containers/SpecificationContainer.jsx, src/routes/metadata/components/MetaDataPanel.jsx
Product templates use `sections` instead of `questions`.
This PR can be merged after migration script is run to the Project Service https://github.com/topcoder-platform/tc-project-service/pull/317
Issue https://github.com/appirio-tech/connect-app/issues/3107
winning submission from challenge 30093923 - Topcoder Connect - Product template update
=> Product templates use sections

package.json
draft-js library update causing too many errors with `convertFromRaw` method calls for `Cannot read property 'length' of undefined`
=> Fixing the version of draft-js as the latest release is causing troubles with connect’s message rendering

src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/MessagesTabContainer.jsx, src/projects/reducers/projectTopics.js, src/projects/routes.jsx
Fix redirecting old URLs to the comments https://connect.topcoder.com/projects/1234#comment-1234456789 to the new messages tab https://connect.topcoder.com/projects/1234/messages/12345#comment-1234456789
Fix also, containing a fix for more general issue `isLoading` didn't represent loading status of topics correctly, as we loaded two kind of topics in parallel, and soon as one type of topics was loaded `isLoading` became `false` though another type of topics may be still loading.
Also, fix refactors approach for handling redirecting topics:
- we don't load Dashboard container just to redirect to the message tab, redirecting happens before loading Dashboard container.
- redirecting is processed inside Messages tab container as that container should be responsible for loading topics in the …
=> Hotfix/post release 2.4.13.6 

src/helpers/markdownToState.js
Fix for the issue with rendering `>` in DraftJS.
The root of the issue is that in code we create a block first, and after when we find `inline` content inside that block we set some properties of the block like `text`. But if there is no inline content, then such properties of the block stay unutilized which causes an error later as a block is not fully defined.
So the solution is set the default values of properties for the block as it has empty inline content. And if there is some inline content, such properties would be updated.
=> Hotfix/post release 2.4.13.7

src/reducers/templates.js
#3180  
Error message has been already shown by alert popup.
Error page will be only shown for error code 500 (as hard-coded for the CoderBot).
https://github.com/appirio-tech/connect-app/blob/b2022930027fa7e0e97cd1a42e0373ed0b70cdb3/src/routes/metadata/containers/ProjectTemplatesContainer.jsx#L117
=> Fix for issue #3180

src/projects/reducers/projectSearch.js
@vikasrohit this is a small fix I've done to the patch after the testing. The loading indicator wasn't shown after pressing Join/Decline buttons in the Card view.
=> Hotfix/post release 2.4.15.2 (small fix)

src/components/AuthenticatedComponent.jsx
This hotfix contains a fix: keep the whole URL when redirecting after log-in. This is to support issue https://github.com/appirio-tech/connect-app/issues/3311.
When we navigate to any page being logged-out we are redirecting to login page. The same time we should keep the FULL URL which we have before so after login we can redirect back to the same page we were trying to navigate.
Before this fix we only keep a part of URL so sometimes we redirect back not to the exact page we were going to initially.
=> [Hotfix] [DEV] post release 2.4.15.3

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
fix: error during changing selected categories
If we select a category, after select skills and after change the list of selected categories there would be an error. It's fixed.
Ref issue #3369
=> [PROD] [HOTFIX] support Skills questions showing all skills without filtering by categories, part 2

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
fix: error during changing selected categories
If we select a category, after select skills and after change the list of selected categories there would be an error. It's fixed.
Ref issue #3369
=> [DEV] [HOTFIX] support Skills questions showing all skills without filtering by categories, part 2

src/projects/reducers/project.js
Fix for issue https://github.com/appirio-tech/connect-app/issues/3386 in PROD
NOTE: that issue above on PROD could be slightly different than reported above. On PROD/DEV it shows Join Project dialog for some moment, but after it hides it and performs approve/decline action successfully.
After the fix, the Join Project dialog is not shown anymore.
=> [HOTFIX] [PROD] fix: approve/decline copilot

src/components/AuthenticatedComponent.jsx
This hotfix contains a fix: keep the whole URL when redirecting after log-in. This is to support issue https://github.com/appirio-tech/connect-app/issues/3311.
When we navigate to any page being logged-out we are redirecting to login page. The same time we should keep the FULL URL which we have before so after login we can redirect back to the same page we were trying to navigate.
Before this fix we only keep a part of URL so sometimes we redirect back not to the exact page we were going to initially.
=> [Hotfix] [PROD] post release 2.4.15.3

src/helpers/utils.js, src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
https://github.com/appirio-tech/connect-app/issues/3494
=> #3494 sync businessPhone validation with member api

src/projects/create/components/ProjectWizard.jsx
#3472   
Retain previously filled wizard data (if any) when choosing the same template
=> Fix for Issue #3472 Keep form data for the same template

src/config/constants.js, src/projects/detail/components/EditProjectDefaultsForm/EditProjectDefaultsForm.jsx
reading from constants file in src folder instead of reading from root (which only works with circle ci)
=> Fixing env variable reading for NDA Terms

src/projects/detail/components/JobPickerRow/JobPickerRow.jsx
remove the following values from the Role dropdown: `QA Tester`  and `QA Engineer`
Before:
After:
=> [DEV] [HOTFIX] remove 2 roles from TaaS Intake Form
