appirio-tech/connect-app

src/middleware/apiMiddleware.js, src/projects/list/actions/loadProjects.js, src/projects/list/components/ProjectListItem/ProjectListItem.jsx
-- Fixed project load after incorporating the api middleware
=> AS#160071805908634, Handle jwt token in api calls

src/projects/detail/components/Specification.jsx, src/projects/detail/components/Specification.scss
=> AS#166070325696606, Project specification style fixes

src/components/TopBar/TopBar.jsx
-- fixed logout link to use accounts app logout url
-- Removed dashboard link
-- used absolute link to help help
@parthshah fyi
=> AS#148343855905798, Top bar - Logged in state

src/actions/loadUser.js, src/api/users.js, src/components/Layout/Layout.jsx
@parthshah fyi, please let me know if we can improve things here
=> Fixed error in loading user's profile image in topbar

src/projects/create/components/AppProjectForm.jsx, src/projects/create/components/CreateProject.scss, src/projects/create/components/GenericProjectForm.jsx
-- Rewritten(after getting changes lost in merge from dev) the changes for fixing the create project screen
=> AS#166070325696601, Fix styles of create project screen

src/projects/FeatureSelector/CustomFeatureForm.jsx, src/projects/FeatureSelector/DefaultFeatureForm.jsx, src/projects/FeatureSelector/FeatureForm.scss, src/projects/FeatureSelector/FeaturePicker.jsx, src/projects/FeatureSelector/FeaturePicker.scss, src/projects/FeatureSelector/FeaturePreview.scss, src/projects/FeatureSelector/PickerFeatureList.jsx, src/projects/FeatureSelector/PickerFeatureList.scss, src/projects/detail/components/Specification.scss
-- Styled as per initial artwork png
@parthshah fyi
=> AS#175328444802917, style feature picker based on new designs

src/components/Layout/Layout.jsx, src/components/TopBar/TopBar.jsx
-- Adapted use of Avatar component to render the avatar based on use's name or handle if profile pic is not available.
@parthshah fyi
=> AS#175328444802920, Update User Avatar to generate a placeholder image based on user's initials.

src/components/LinksMenu/DeleteLinkModal.js, src/components/LinksMenu/LinksMenu.js, src/components/LinksMenu/LinksMenu.scss, src/components/TopBar/TopBar.jsx, src/projects/create/components/AppProjectForm.jsx, src/projects/create/components/CreateView.jsx, src/projects/create/components/GenericProjectForm.jsx, src/projects/detail/Dashboard.scss
Fixes till date for v2_beta issues
fyi @fnisen @parthshah @mahestro @talesforce @ajefts
=> v2_beta issues fixes

src/projects/create/components/CreateView.jsx, src/projects/list/components/Projects/Projects.jsx, src/projects/list/components/Projects/ProjectsView.jsx, src/projects/list/components/Projects/ProjectsView.scss, src/projects/list/components/ProjectsToolBar/ProjectsToolBar.jsx, src/projects/routes.jsx
PR for #39 
fyi, @fnisen @mahestro @vic-appirio
=> Project creation: disable top navigation when in Project creation

src/components/TeamManagement/AddTeamMember.jsx, src/projects/detail/containers/TeamManagementContainer.jsx
-- Fixed. Now it shows appropriate error message when member is already in the team
=> AS#181122346682547, Dashboard/Team management: search validation message incorrect when user already on team

src/components/FooterV2/FooterV2.js, src/components/FooterV2/FooterV2.scss, src/projects/create/components/CreateView.jsx
=> Fix Other Work tab visualization for user roles and footer in left panel

src/projects/detail/containers/TeamManagementContainer.jsx
=> Github issue #75 : Dashboard/Team management: search validation message incorrect when user already on team

src/projects/list/components/Projects/ProjectsView.jsx, src/projects/list/components/Projects/ProjectsView.scss
-- Implemented required changes
=> Github issue #102 Project Listing: redesign

src/components/Feed/NewPost.jsx, src/projects/detail/Dashboard.scss
-- Fixed background for the collapsed composer
-- Fixed extra space in bottom of the collapsed composer
-- Fixed close button functionality and visibility
=> Github issue #153  Dashboard: Compose update collapsed is not to speck

src/components/Feed/NewPost.jsx, src/components/Feed/draftjs.scss, src/components/MessageList/MessageList.jsx, src/components/MessageList/MessagingEmptyState.jsx, src/components/TopBar/ProjectToolBar.js, src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/MessagesContainer.js, src/projects/routes.jsx
-- Done copy changes. Changed the url(/messages => /discussions) as well to reflect the same nomenclature.
fyi, @fnisen we can merge it after bug hunt.
=> Github issue #307 Messages: changes "Messages" to "Discussions"

src/components/TeamManagement/TeamManagement.jsx
-- Fixed, fyi @parthshah please let me know you see any problem with the changes.
=> Github issue #355 Delete Confirmation popup overlay is opened center aligned to the list

src/components/FileList/FileListItem.jsx
=> Github issue #267 throwing error on saving blank name of uploaded file

src/components/LinksMenu/AddLink.jsx
-- Relaxed the URL validation to be similar as with member profile in members app
=> Github issue #467 Links: critical problems with view and validation

src/components/FileList/AddFiles.jsx, src/components/FileList/AddFiles.scss
-- Updated AddFiles component to accommodate the changes in FilePicker component
Accompanying PR for https://github.com/appirio-tech/react-components/pull/99
=> Github issue #196 specification: last uploaded file name displayed on the upload section

src/components/LinksMenu/DeleteLinkModal.jsx, src/components/LinksMenu/LinksMenu.scss, src/components/Modal/Modal.scss, src/components/ProjectInfo/DeleteProjectModal.js, src/components/ProjectInfo/ProjectInfo.scss, src/components/ProjectStatus/ProjectStatus.scss, src/components/ProjectStatus/ProjectStatusChangeConfirmation.jsx, src/components/TeamManagement/DeleteModal.jsx, src/components/TeamManagement/TeamManagement.scss
-- Fixed modal styles to match with specs for left panel of the project specs page
=> Github issue #244 [Project Dashbord] No confirmation on project status change

src/components/TeamManagement/AddTeamMember.jsx, src/components/TeamManagement/TeamManagement.scss
-- Fixed styles as per requirements mentioned in the issue description
=> Github issue #466 Team management: "member/copilot" switch fixes

package.json, src/components/ProjectInfo/ProjectInfo.jsx, src/components/ProjectInfo/ProjectInfo.scss, src/components/ProjectType/ProjectType.jsx, src/config/projectQuestions/topcoder.v1.js, src/projects/detail/containers/ProjectInfoContainer.js
-- Added description to dashboard and specification pages
=> Github issue #469 Add project "Description" to Dashboard and Specifications

src/components/App/App.scss, src/components/FileList/FileDeletionConfirmModal.jsx, src/components/FileList/FileList.scss, src/components/FileList/FileListItem.jsx
-- Added confirmation modal before deleting a file from the specifications page. Right now it is full page modal, will try with localised modal after this change.
=> Github issue #468 File upload: confirm deletion

src/components/ColorSelector/ColorSelector.jsx, src/components/ColorSelector/ColorSelector.scss
-- Added desire behaviour to improve the color removal experience
=> Github issue #317 [Specification] - no option to remove the color added

src/projects/detail/Dashboard.jsx
-- Potential fix for the problem.
=> Github issue #245 Can't scroll down the page when user click 'Add' from Project Team

src/assets/images/tech-32px-outline-work-project.svg, src/components/ProjectType/ProjectType.jsx, src/components/ProjectType/ProjectType.scss
Added new icon and code changes to display it for generic project. @vikasrohit review and refactor if needed; the current solution disables the empty div generated
=> Fixes #375;

src/projects/detail/containers/TeamManagementContainer.jsx
-- Fixed via community (submission-232870-submission-v2.zip) - utkarshkukreti
Also, fixes #245
=> Github #465 Team management: "member/copilot" switch not visible when there are 3+ team members

src/routes.jsx
-- Fixed. Now user would be taken to the login page first.
=> Github issue #518 Discussions URL shows empty page when user is not logged in

src/config/projectQuestions/topcoder.v1.js
=> Updating topcoder.v1.js with copy change

src/projects/create/components/GenericProjectForm.jsx
Changed "invite" code to "reference" code.
=> Updating copy in GenericProjectForm.jsx

src/projects/create/components/AppProjectForm.jsx
Changed "invite" code to "reference" code
=> Updated copy on AppProjectForm.jsx

src/config/projectQuestions/topcoder.v1.js
Sans Serif icon represented incorrectly
=> Updating topcoder.v1.js with icon change

src/components/TeamManagement/TeamManagement.scss
-- Got it fixed via community. Thanks to ksladkov for awesome work.
=> Github issue #520 Dashboard || Scroll issue when adding team member (Windows)

src/components/TeamManagement/AutoCompleteInput.jsx, src/config/constants.js, src/projects/detail/containers/TeamManagementContainer.jsx
=> Github issue #351 [Add a Team Member] - the existing username is displayed as autocomplete when set focus

src/components/MessageList/MessageList.jsx
=> Github issue #522 Discussions || Left side panel does not have scroll in Safari

src/projects/detail/components/EditProjectForm.jsx
=> Github issue #252 Clicking on 'Save Changes' button 2-3 times will display 'Project updated.' message 2-3 times

src/components/ActionCard/ActionCard.scss, src/projects/detail/components/SidebarNav.jsx
@parthshah please review and merge
=> Post overrides

src/components/LinksMenu/AddLink.jsx
Changed titles for "Add Link" fields
=> Updating copy on AddLink.jsx

src/components/TopBar/TopBar.jsx, src/components/TopBar/TopBarContainer.js, src/projects/list/components/Projects/Projects.jsx
=> Github issue #543, Change project name search to project keyword search

src/config/constants.js, src/index.html, src/index.jsx
Will need to change the heap.load ID in prod
=> Update index.html to add Heap Analytics tracking

src/projects/list/components/Projects/Projects.jsx
-- Fix from community: Winner: suisl
=> Github issue #552, Project listing: return user to previous spot in listing after back from project

src/components/TopBar/TopBar.jsx
-- Fixed logout issue in Safari
=> Github issue #566, Connect Login/Logout redirect not working correctly in Safari

src/components/TeamManagement/TeamManagement.scss
=> Github issue #360, Even though user clear the username from the textbox using (x) button, Can add the user by clicking the ADD button

src/components/Footer/Footer.jsx
Updating footer Help link to point to new Connect FAQ instead of general help page
=> Updating footer Help link

src/components/TopBar/TopBar.jsx
@parthshah @vikasrohit Push this when we're ready to remove the beta logo.
=> Switch the Beta logo with the original Connect logo

src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/MessagesContainer.js
-- Fixed edge case where a reply to a topic was not being persisted after loading more posts for a topic
=> Github #166, Messaging: unposted content alert

src/projects/detail/containers/MessagesContainer.js
-- Added footer for the discussion page
=> Github issue #574, Discussions: no footer on Discussion tab

src/routes.jsx
-- Added redirect to connect from connectv2
@parthshah fyi, please let me know if you see any troubles with these changes.
=> Github issue#561, General: Redirect connectv2.topcoder.com to connect.topcoder.com

src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/MessagesContainer.js
-- Ignored empty posts whose author are 'system'
@parthshah fyi
=> Github issue#585, Ignore 'user-joined' type posts in Topic comments

src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/MessagesContainer.js, src/projects/reducers/projectTopics.js
=> Github issue #596, Status update: a comment post remains in the composer window after being posted

src/api/messages.js
-- Done. But not tested yet. Not sure how to validate that axios is actually respecting the new timeout. There are few issues mentioned in web community about axios not respecting the timeout settings in some cases.
@parthshah fyi, I think these changes should be enough, but not able to test them.
=> Github issue #593, Increase timeout when posting topics / comments to message service

src/components/Grid/GridView.scss
-- Fixed font styles for the tooltip
=> Github issue #372, [Pagination] - keep fixed pagination option displaying 5 pages.

src/projects/detail/Dashboard.scss
=> Github issue #607, Dashboard: status updates overflowing container

src/components/ActionCard/ActionCard.scss
=> Github issue#619, Dashboard: comment post overflowing container

src/components/Feed/FeedComments.jsx, src/components/MessageDetails/MessageDetails.jsx
=> Github issue#625, Project 908: Dashboard stuck in infinite loop

src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/MessagesContainer.js
-- Done, now any team member of the project can comment on even system posts
=> Github issue#623, Allow comments for System generated messages / status updates.

src/components/TopBar/TopBar.jsx, src/config/constants.js, src/index.jsx, src/projects/actions/projectTopics.js, src/routes.jsx
- Github issue#619, Dashboard: comment post overflowing container
- Github issue#625, Project 908: Dashboard stuck in infinite loop
- Github issue#623, Allow comments for System generated messages / status updates.
- Analytics Hot Fix
fyi @fnisen @parthshah
=> Promoting to prod before Products MVP

src/projects/detail/containers/ProjectInfoContainer.js
-- Showing support link instead of not showing direct project link
=> Github issue #610, In UI, handle Direct project not being set

src/projects/create/components/ProjectWizard.jsx
=> Github issue #652, After project is created, user should be taken to Dashboard, not Specification

src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/topcoder.v2.0.js, src/config/projectSpecification/typeToSpecification.json
Defined new template for v2 with target type being in specification page
=> Github issue #659, Defined v2 of fallback template

src/projects/detail/components/SpecSection.jsx, src/projects/detail/containers/Specification.scss
-- Editable project name only for draft project
=> Github issue #654, Project name should be editable when project is first created

src/projects/detail/components/VisualDesignProjectEstimateSection.jsx
=> Fix currency formatting in quick quote

src/config/projectQuestions/avd.v1.0.js
=> Screen number options in project specification

src/components/Home/Home.scss
=> Github issue#678, Landing page (not logged in) with broken layout

src/projects/detail/components/ProjectSpecSidebar.jsx, src/projects/detail/components/SpecScreens.jsx
-- Fixed bug which occurred after removing optional behaviour of the number of screens question.
fyi @gondzo
=> Github issue #677, Wire "quick quote" feature on Specification

src/config/projectWizard/index.js, src/projects/create/components/ProjectWizard.jsx, src/projects/detail/containers/SpecificationContainer.jsx
=> Save product type into project.details

src/components/ProjectType/ProjectType.jsx, src/config/projectQuestions/avd.v1.1.js, src/config/projectQuestions/topcoder.v2.0.js, src/config/projectQuestions/wireframes.v1.0.js, src/config/projectSpecification/typeToSpecification.json, src/config/projectWizard/index.js, src/projects/detail/components/EditProjectForm.jsx, src/projects/detail/components/ProjectSpecSidebar.jsx, src/projects/detail/components/SpecQuestions.jsx, src/projects/detail/components/SpecSection.jsx, src/projects/detail/components/VisualDesignProjectEstimateSection.jsx, src/projects/detail/containers/ProjectInfoContainer.js, src/projects/detail/containers/Specification.scss
-- Attempt to resolve most the requirements mentioned in the doc https://docs.google.com/document/d/11d2uXJTg_zeVTviUTI1sM5BWfKLIluC56AnKbSv7wl4/edit
=> Specification content order/structure fixes

src/projects/detail/containers/ProjectInfoContainer.js
=> Github 610, In UI, handle Direct project not being set

src/projects/detail/components/SpecQuestionList/SpecQuestionList.scss, src/projects/detail/containers/Specification.scss
Fixing the min-height for text areas in the project specification
=> textarea min-height fixed for 1 row height.

src/components/ProjectStatus/ProjectStatus.js, src/components/ProjectStatus/ProjectStatus.scss, src/components/ProjectStatus/ProjectStatusChangeConfirmation.jsx
-- Copy changes
-- put validation for empty cancel reason
=> [DO NOT MERGE UNTIL BUG HUNT CONCLUDES] Github issue #44, Add support for reason for project cancelation

src/projects/detail/components/SeeAttachedWrapperField.jsx, src/projects/detail/components/SpecQuestionList/SpecQuestionList.jsx, src/projects/detail/components/SpecQuestions.jsx
Issue #675
@gondzo as we discussed via Slack I made the following changes:
=> Restructure skip question component

src/projects/detail/components/SeeAttachedWrapperField.jsx, src/projects/detail/components/SpecQuestions.jsx
=> Fix support text area classname for empty state

src/projects/create/components/SelectProjectType.jsx, src/projects/create/components/SelectProjectType.scss
fixed #766 added visited class and corrected link text
=> fixed #766 added visited class and corrected link text

src/projects/detail/containers/Specification.scss
fixed #773 removed css for span element
=> fixed #773 removed css for span element

src/reducers/alerts.js
Fixed #727 Error if update project without project name on specification page
=> fixed #727 Error if update project without project name on specification page

src/projects/create/components/SelectProjectType.jsx
fixed #701 checking trimmed input value
=> fixed #701 checking trimmed input value

src/projects/detail/components/SidebarNav.jsx
https://github.com/appirio-tech/connect-app/issues/761
=> Issue 761: Fix for question count

src/projects/detail/components/SidebarNav.jsx
Reverts appirio-tech/connect-app#810
=> Revert "Issue 761: Fix for question count"

src/components/TopBar/TopBar.scss
=> fix #726 new project button is gray

src/projects/create/components/WizardHeader.scss
=> fix #732 clear button on IE

src/projects/detail/components/SpecScreens.jsx
=> fix #700 Screens limit

src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/avd.v1.1.js, src/config/projectQuestions/wireframes.v1.0.js, src/projects/detail/components/SpecScreenQuestions.jsx
fixed #737 isRequired validations for specs
=> fixed #737 isRequired validations for specs

src/projects/detail/components/VisualDesignProjectEstimateSection.scss
https://github.com/appirio-tech/connect-app/issues/740
=> fixed IE11 css alignment issue in project estimate

src/projects/detail/components/SpecSection.jsx
https://github.com/appirio-tech/connect-app/issues/779
=> Issue 779: fixed required field markings

src/projects/detail/components/SidebarNav.jsx
https://github.com/appirio-tech/connect-app/issues/761
=> issue 761: fixed progress indicator to only show with questions

src/projects/detail/components/ProjectSpecSidebar.jsx, src/reducers/alerts.js
https://github.com/appirio-tech/connect-app/issues/670
=> Issue 670: Added project submit alert and redirect to dashboard

src/projects/detail/components/SpecQuestions.jsx
=> Github issue #836, Remove skip question option for primary target device question

src/config/projectQuestions/app_dev.v1.0.js, src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/visual_design.v1.0.js, src/config/projectQuestions/wireframes.v1.0.js
=> Fix inactive 'submit for review' button

src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/wireframes.v1.0.js, src/projects/detail/components/SpecQuestionList/SpecQuestionList.jsx, src/projects/detail/components/SpecQuestions.jsx
=> Remove skip question option from design guidelines

src/config/projectSpecification/typeToSpecification.json
=> fix template for 'Other Design'

src/projects/detail/components/ProjectSpecSidebar.jsx
=> Fix empty screen for 'Other design' projects

src/projects/detail/components/EditProjectForm.jsx, src/projects/detail/components/SpecScreens.jsx
=> Fix unnecessary unsaved changes warning

src/projects/detail/components/EditAppScreenForm.jsx, src/projects/detail/components/SpecScreens.jsx, src/projects/detail/containers/Specification.scss
-- Added the delete button to the new place. It works well, however, the desired behaviour(as mentioned here https://github.com/appirio-tech/connect-app/issues/767#issuecomment-285543113) is not achieved yet. It has some issues with validations which are being handled by 751.
=> Github issue#767, Specification-App Screen: redesign button alignment for Delete screen/Define screen/Save

src/projects/detail/containers/ProjectInfoContainer.js
=> Github issue#610, In UI, handle Direct project not being set

src/config/constants.js, src/projects/actions/projectTopics.js
=> updating coderbot value and fixes system hardcoded values

src/projects/detail/components/ProjectSpecSidebar.jsx
-- Trimmed form field value, before checking if it is empty or not, if it is a string.
=> Github issue#405, White spaces are recognized as valid input for NOTES

src/projects/create/components/ProjectWizard.jsx, src/projects/create/containers/CreateContainer.jsx, src/routes.jsx
— Implemented required behaviour on ad hoc basis instead of enabling the Wizard or ProjectWizard component for being URL aware.
=> Github issue#1035, URL does not change when selecting project from "New Project" page

package.json, src/config/constants.js, src/projects/create/containers/CreateContainer.jsx, src/projects/detail/components/SpecSection.jsx
— Disabled the ref code box if it is loaded from query params
=> Github issue#1102, Process/add ref code from deep link

README.md
@vikasrohit just fixed a little of the README
=> small README fix

src/config/projectQuestions/app_dev.v1.0.js, src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/ibm_chatbot.v1.0.js, src/config/projectQuestions/topcoder.v1.js, src/config/projectQuestions/visual_design.v1.0.js, src/config/projectQuestions/wireframes.v1.0.js
— copy changes as per https://github.com/appirio-tech/connect-app/issues/1033#issuecomment-319538300
=> Github issue#1033, Other Design's Project Name field error message is empty

src/config/projectQuestions/ibm_chatbot.v1.0.js
=> cleaned up ibm chat bot

src/projects/create/components/ProjectWizard.jsx
=> Github issue#1127, Checkbox group type questions not removing unselected items

src/config/projectQuestions/ibm_chatbot.v1.0.js
— Removed required validation for description field
Github issue#1131, Chatbot: spec page not showing validation errors
— Added generic validations
=> Github issue#1133, Chatbot: "Save changes" button is enabled, but not working when validation is triggered

src/projects/create/containers/CreateContainer.jsx
discussed here https://github.com/appirio-tech/connect-app/issues/1037#issuecomment-324732052
=> Removing unsaved content alerts

npm-shrinkwrap.json, src/api/projects.js, src/components/TopBar/ProjectToolBar.js, src/projects/create/containers/CreateContainer.jsx, src/projects/detail/components/ProjectToolBar/ProjectToolBar.jsx
@gondzo new challenges will have `project.details.hideDiscussions = true` and the **Discussions** link is hidden from the header for those challenges.
Let me know if that's what you wanted.
=> Phase out discussions

src/config/projectQuestions/ibm_chatbot.v1.0.js
=> Github issue#1131, Chatbot: spec page not showing validation errors

src/components/TopBar/ProjectsToolBar.scss
=> Github issue#1164, ProjectWizard steps have misaligned title in modal mode

src/projects/create/containers/CreateContainer.jsx
Github issue#1114, Save incomplete project even if there is no change in form
=> Saving project to local storage even if there is not change

src/components/TopBar/ProjectsToolBar.js, src/components/TopBar/TopBarContainer.js, src/projects/routes.jsx, src/routes.jsx
Github issue#1110, Unsaved content warning not appearing for logged in 'New Project' flow
=> Added unsaved content alert to new project modal

npm-shrinkwrap.json
=> Github issue#1181, Fix the salesforce lead link for the new org

src/config/projectQuestions/real_world_testing.v1.0.js, src/config/projectSpecification/typeToSpecification.json, src/config/projectWizard/index.js
Changed Crowd Testing product name to Real World Testing and added additional questions to intake form.
=> Real World Testing Enablement

src/styles/_fonts.scss
fixes #1165 changed fonts path from absolute to relative
=> fixes #1165 changed fonts path from absolute to relative

src/config/projectWizard/index.js, src/projects/create/components/ProjectTypeCard.scss, src/projects/create/components/SelectProjectType.jsx
=> Github issue#1218, Proper fix for hiding any project category

src/components/Feed/draftjs.scss, src/projects/create/components/ProjectOutline.scss
The following fix wraps issue #1192
=> Fix for #1192 and #1064

src/config/projectQuestions/app_dev.v1.0.js, src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/generic_chatbot.v1.0.js, src/config/projectQuestions/ibm_chatbot.v1.0.js, src/config/projectQuestions/real_world_testing.v1.0.js, src/config/projectQuestions/visual_design.v1.0.js, src/config/projectQuestions/wireframes.v1.0.js, src/config/projectSpecification/typeToSpecification.json, src/config/projectWizard/index.js, src/projects/create/components/ProjectWizard.jsx, src/projects/create/containers/CreateContainer.jsx, src/projects/list/components/Projects/ProjectsView.jsx, src/routes.jsx
=> project wizard supporting customizable seo url

src/projects/create/components/ProjectWizard.jsx, src/projects/create/containers/CreateContainer.jsx
=> optimize incomplete project screen behaviour

src/projects/create/components/FillProjectDetails.js, src/projects/create/components/IncompleteProjectConfirmation.js, src/projects/create/components/ProjectWizard.jsx, src/projects/create/components/SelectProduct.js, src/projects/create/components/SelectProjectType.jsx, src/projects/create/components/_layout.scss, src/projects/create/containers/CreateContainer.jsx
— Fixed Logo, Back and Close buttons for both logged in and logged out views
=> Github issue#1234, Functions of the "Connect Logo", "Back", "Esc" buttons in logged in and logged out states

npm-shrinkwrap.json, package.json, src/config/constants.js, src/projects/create/containers/CreateContainer.jsx
— Front end changes to pass the required google analytics fields with project data
=> Github issue#1227, Google Analytics ID + Click ID integration for marketing

src/config/projectQuestions/mobility_testing.v1.0.js
— Fixed issue in opening project in edit mode
=> Github issue#1198, Mobility Testing product on Connect

src/projects/detail/containers/Specification.scss
=> Change Watson Chatbot project title

src/config/projectQuestions/app_dev.v1.0.js, src/config/projectQuestions/avd.v1.0.js, src/config/projectQuestions/real_world_testing.v1.0.js, src/config/projectQuestions/topcoder.v1.js, src/config/projectQuestions/visual_design.v1.0.js, src/config/projectQuestions/wireframes.v1.0.js, src/projects/create/components/ProjectTypeCard.scss, src/projects/detail/containers/Specification.scss
Fixed #1271, #1278, #1279, #1280
=> Community fixes 02

src/components/LinksMenu/LinksMenu.scss
fixed line height issue with sidebar menu links
=> fix_for_#1313

src/projects/create/components/ProjectOutline.js, src/projects/create/components/ProjectOutline.scss
Reverts appirio-tech/connect-app#1342
=> Revert "Fix #1338 Project creation outline panel should use the project dashboard styles"

src/projects/create/components/ProjectOutline.js, src/projects/create/components/ProjectOutline.scss
Reverts appirio-tech/connect-app#1356
=> Fix #1338 Project creation outline panel should use the project dashboard styles

src/components/ActionCard/ActionCard.scss, src/components/Feed/draftjs.scss
=> fixes #1366 styling issues

src/api/projectMembers.js, src/api/projects.js, src/assets/images/arrow-6px-carret-down-active.svg, src/assets/images/arrow-6px-carret-down-normal.svg, src/assets/images/check-dark.svg, src/assets/images/external-link.svg, src/assets/images/grid-list-ico.svg, src/assets/images/status-ico.svg, src/components/Grid/GridView.scss, src/components/Grid/ListItem.jsx, src/components/ProjectStatus/ProjectStatus.jsx, src/components/ProjectStatus/editableProjectStatus.js, src/components/TopBar/Filters.js, src/projects/actions/loadProjects.js, src/projects/list/components/Projects/ProjectListNavHeader.jsx, src/projects/list/components/Projects/ProjectListNavHeader.scss, src/projects/list/components/Projects/ProjectListTimeSortColHeader.jsx, src/projects/list/components/Projects/ProjectSegmentSelect.jsx, src/projects/list/components/Projects/Projects.jsx, src/projects/list/components/Projects/ProjectsGridView.jsx, src/projects/list/components/Projects/ProjectsGridView.scss
https://github.com/appirio-tech/connect-app/issues/1376
=> Issue 1376

src/assets/images/ui-16px-2_grid-45-gray.svg, src/components/Grid/GridView.scss, src/components/Layout/Layout.scss, src/projects/list/components/Projects/ProjectListNavHeader.scss, src/projects/list/components/Projects/ProjectsGridView.jsx, src/projects/list/components/Projects/ProjectsGridView.scss
https://github.com/appirio-tech/connect-app/issues/1376#issuecomment-350909984
=> Issue 1376: CSS modifications

src/components/TopBar/Filters.js
=> fix clear filters button styles

src/projects/list/components/Projects/ProjectsGridView.jsx
=> Increase project grid click zone

src/projects/list/components/Projects/ProjectsGridView.jsx
=> Prevent app from crashing when last editor is not defined

src/config/constants.js, src/projects/list/components/Projects/ProjectListNavHeader.jsx
=> Change status tabs order & labels

src/components/CoderBot/CoderBot.scss
=> fix error message position in grid view

src/components/TopBar/ProjectsToolBar.js
=> Remove selected tab from filters count

src/projects/list/components/Projects/ProjectsGridView.scss
=> Fix cancel project modal in grid view

src/components/TopBar/ProjectsToolBar.js
=> persist toolbar filter state in sessionStorage

src/components/Grid/GridView.jsx, src/components/Grid/Placeholder.jsx, src/components/Grid/Placeholder.scss
=> Fix lazy-load performance and add placeholders

src/components/User/UserTooltip.jsx, src/components/User/UserTooltip.scss
related issue #1445
@gondzo can you check this one so I can move to #1444 ?
=> Update UserTooltip component

src/api/projects.js, src/components/TopBar/ProjectsToolBar.js, src/projects/actions/project.js, src/projects/list/components/Projects/Projects.jsx, src/projects/reducers/project.js, src/reducers/alerts.js
=> Prevent redirecting when updating status in grid view

src/components/User/UserTooltip.jsx, src/components/User/UserTooltip.scss, src/projects/list/components/Projects/ProjectManagerAvatars.jsx, src/projects/list/components/Projects/ProjectManagerAvatars.scss, src/projects/list/components/Projects/ProjectsGridView.scss
=> Add tooltip for managers

src/projects/list/components/Projects/ProjectManagerAvatars.jsx
=> Remove double avatars from managers in grid view

src/components/ActionCard/Comment.jsx, src/components/Feed/Feed.jsx, src/components/ScrollToAnchors.jsx, src/config/constants.js, src/projects/detail/components/SpecSection.jsx, src/routes.jsx, src/routes/notifications/constants/notifications.js, src/routes/notifications/helpers/notifications.js
issue #1464 - added routes for a specific post, topic and project file
Example links (in local env):
- topic http://local.topcoder-dev.com:3000/projects/2201/#feed-1533
- post http://local.topcoder-dev.com:3000/projects/2201/#comment-5797
- files list http://local.topcoder-dev.com:3000/projects/2205/specification#appDefinition-files
For posts and topics time is a link
=> issue #1464 - added routes for specific post, topic and project file

src/routes/notifications/constants/notifications.js, src/routes/notifications/helpers/notifications.js
Issue #1468 - support for “[Who] responded to your post” notifications
NOTE, to make this work this PR in tc-notifications has to be applied https://github.com/topcoder-platform/tc-notifications/pull/5
=> Issue #1468 - support for “[Who] responded to your post” notifications

src/routes/settings/components/SettingsToolBar.jsx, src/routes/settings/routes.jsx
Issue #1511 - Hide "Profile" and "System" from Settings section
=> Issue #1511 - Hide "Profile" and "System" from Settings section

src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx, src/config/constants.js, src/routes/notifications/containers/NotificationsContainer.jsx
=> Set interval to update notifications

src/components/NotificationsDropdown/NotificationsDropdown.scss, src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx
issue #1519 - Screen flicker in dropdown
Removed noScroll class
=> issue #1519 - Screen flicker in dropdown

src/components/TopBar/Filters.js
=> Hide segment filter

src/routes/settings/components/SettingsPanel.jsx, src/routes/settings/components/SettingsPanel.scss, src/routes/settings/routes/notifications/containers/NotificationSettingsContainer.jsx
=> Replace Notifications center help text

src/components/TopBar/ProjectsToolBar.js
=> Hide filters after logout

src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx, src/config/constants.js
=> Update notifications dropdown to show all notifications per project

src/components/TopBar/ProjectToolBar.js, src/components/TopBar/ProjectToolBar.scss
=> Fix header icons

src/routes/notifications/helpers/notifications.js
=> Remove global notifications section if is 0

src/components/TopBar/TopBarContainer.js, src/components/TopBar/TopBarContainer.scss
=> Replace app colorful logo with b/w logo

src/components/ProjectStatus/editableProjectStatus.js, src/components/ProjectStatusSection/ProjectStatusSection.js, src/config/constants.js
=> Fix order of statuses in dropdown menu

src/components/ProjectInfo/ProjectInfo.jsx, src/projects/list/components/Projects/ProjectCardBody.jsx
=> Fix issue with the read more link in project info

src/components/TopBar/ProjectsToolBar.js
=> Fix issue with 0 shown at the topbar when user is not logged in

src/projects/detail/components/EditProjectForm.jsx, src/projects/detail/components/SpecQuestionList/SpecQuestionList.scss, src/projects/detail/components/SpecSection.jsx
issue #1368 
@vic-topcoder @gondzo fyi
=> Fix text area auto-sizing

src/projects/list/components/Projects/ProjectCard.jsx, src/projects/list/components/Projects/ProjectCard.scss
Issue #1351 - Don't wrap ProjectCard in Link, instead handle click event
=> Issue #1351 - Don't wrap ProjectCard in Link, instead handle click event

src/config/constants.js, src/projects/actions/loadProjects.js, src/projects/list/components/Projects/ProjectListNavHeader.jsx, src/projects/list/components/Projects/Projects.jsx, src/projects/reducers/projectSearch.js
Issue #1563 - Non persistent manager interface for card/list switch
=> Issue #1563 - Non persistent manager interface for card/list switch

src/config/constants.js, src/projects/list/components/Projects/Projects.jsx, src/projects/reducers/projectSearch.js
Issues #1557 - Make "Active" project tab default for project listing
=> Issues #1557 - Make "Active" project tab default for project listing

src/components/User/UserTooltip.jsx, src/components/User/UserTooltip.scss
Issue #1533 - Unify the use of the Avatar component on project grid and cards
=> Issue #1533 - Unify the use of the Avatar component on project grid and cards

src/projects/list/components/Projects/ProjectManagerAvatars.jsx
This fixes https://github.com/appirio-tech/connect-app/issues/1580
=> Issue #1580 Fix managers counter not correct on project list

src/components/TopBar/TopBarContainer.js
Fix issue: https://github.com/appirio-tech/connect-app/issues/1539
=> Issue 1539: Provide link to manage profile from user dropdown

src/projects/list/components/Projects/ProjectsGridView.scss
fixes for truncate issue #1573
=> issue #1573 fix

package.json, src/components/Feed/NewPost.jsx, src/components/RichTextArea/RichTextArea.jsx, src/projects/detail/containers/FeedContainer.js
add draft-js-mention-plugin to post text editor.
use @'F_NAME L_NAME' in the text box. 
replace them with @handle before posting to backend
=> Issue #1469 - User mentions in the posts

package.json, src/components/Feed/NewPost.jsx, src/components/RichTextArea/RichTextArea.jsx, src/projects/detail/containers/FeedContainer.js
Reverts appirio-tech/connect-app#1594
=> Revert "Issue #1469 - User mentions in the posts"

config/webpack/default.js, npm-shrinkwrap.json, package.json, src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx, src/routes/notifications/actions/index.js, src/routes/notifications/constants/notifications.js, src/routes/notifications/containers/NotificationsContainer.jsx, src/routes/notifications/helpers/notifications.js
Issue #1544 - Notifications bundle
- Replaced custom templates with Handlebars. After some time of trying to make some clear code moving to handlebars appears to be the best solution.
- Handlebars can solve the issue with [`userHandle`/`userFullName`](https://github.com/appirio-tech/connect-app/issues/1554) by itself in an easier way than versions. So basically we don't need versions for now. Though I didn't replace versions with handlebars. I think we can check what are next requirements and if we need to get rid of versions or no.
=> Issue #1544 - Notifications bundle

src/components/RichTextArea/RichTextArea.jsx
init mention plugin in object instead of in global
=> fix mention bug: mention text adds only to last text box

src/components/TopBar/ProjectsToolBar.js
Project search should not count against total filter applied
=> Issue #1634 - Project search should not count against total filter applied 

src/projects/list/components/Projects/ProjectListProjectColHeader.jsx
sort error object getting passed error has been fixed @gondzo please check
Thanks
=> fix for sort error #1652

src/projects/list/components/Projects/ProjectCard.jsx, src/projects/list/components/Projects/ProjectManagerAvatars.jsx
Limit to 10 max because of min width of a card
=> Issue #1636 - Limit the number of manager profiles on card view to fit

src/components/TopBar/ProjectsToolBar.js, src/projects/list/components/Projects/ProjectListNavHeader.jsx, src/projects/list/components/Projects/ProjectListNavHeader.scss, src/projects/list/components/Projects/Projects.jsx
Move My Projects switch inline with the view switch tab #1632
=> issue-1632 Move My Projects switch inline with the view switch tab

src/config/projectWizard/index.js
Updated the disclaimer content for IBM Chatbot
=> Fixed - IBM Chatbot content updates [HOTFIX]#1684

src/components/NotificationsDropdown/NotificationsDropdown.scss
=> Vertically center the notification bell icon

src/projects/create/containers/CreateContainer.jsx
— Fixed at front end, will add backend fix when we move the logic, of updating salesforce fields, to salesforce.
=> Github issue#1403, Handle null values for gclid - Google Click Id from Connect to Salesforce

config/webpack/development.js, config/webpack/production.js, src/components/NotificationsDropdown/NotificationsDropdown.scss, src/components/ProjectInfo/ProjectInfo.scss, src/components/TopBar/ProjectToolBar.scss, src/components/TopBar/SectionToolBar.scss, src/projects/list/components/Projects/ProjectListNavHeader.jsx, src/projects/list/components/Projects/ProjectsGridView.scss
https://www.topcoder.com/challenges/30062936
=> fixes for #1696

src/components/TeamManagement/DeleteModal.jsx
=> Fix minor typo

src/config/projectQuestions/topcoder.v1.js
=> Fixed missing _ for generic design project types

src/config/projectQuestions/topcoder.v1.js
removed redundant code from generic_design template.
=> Used Common method defined for finding files section title.

src/projects/detail/components/ProjectSpecSidebar.jsx
=> Issue #1799 - Wrong grammar on Submit for review page

src/assets/icons/icon-close.svg, src/assets/icons/icon-save.svg, src/components/FileList/FileListItem.jsx
=> Issue #1780 - tooltip should be corrected

src/projects/list/components/Projects/ProjectsGridView.jsx
=> fix #1728: REF code field adds 'amp;' into '&'

src/routes/settings/routes/notifications/containers/NotificationSettingsContainer.jsx
=> fix #1777: typo on the notification page

src/assets/icons/icon-edit.svg
=> issue #1779 fix

src/components/LinksMenu/LinksMenu.scss
=> fix #1745 #1694: trash icon should be fully clickable

src/config/constants.js
=> fix #1776: change cancelled to canceled for consistency

src/components/Footer/Footer.jsx, src/components/FooterV2/FooterV2.jsx
=> issue 1757 fix

src/projects/detail/components/FeatureSelector/FlattenedFeatureList.jsx
=> fix #1786: After adding the Feature requirement we have UI issue.

src/projects/list/components/Projects/ProjectsCardView.jsx
=> fix #1769: Tile view 'No more Active projects' label have different font

src/projects/list/components/Projects/ProjectsGridView.jsx
=> fix #1764: Year not shown if not current year

src/components/TeamManagement/TeamManagement.scss
=> fix #1758: Add button text not in center

src/components/TeamManagement/MemberRow.jsx
=> fix #1771: Admin is seeing remove icon twice if he is owner 

src/projects/list/components/Projects/ProjectCardHeader.scss
=> issue #1760 fix

src/components/TopBar/ProjectToolBar.js
Fixes https://github.com/appirio-tech/connect-app/issues/1761
=> Fix route matching logic

src/components/TopBar/ProjectsToolBar.js, src/projects/list/components/Projects/ProjectListNavHeader.jsx, src/projects/list/components/Projects/Projects.jsx
=> fix #1749: Search result sorting is incorrect

src/projects/detail/containers/Specification.scss
=> fix #1767: project name overlapped in submitted specification

src/components/FileList/FileList.jsx, src/components/Panel/Panel.scss
Reverts appirio-tech/connect-app#1842
=> Revert "Issue #1787 - should not be able to upload file when the delete confi…"

src/components/ProjectStatus/ProjectStatusChangeConfirmation.jsx
=> fix #1713: Card View-> Cancel button navigates user to project page

src/components/ProjectStatus/ProjectStatusChangeConfirmation.scss, src/projects/list/components/Projects/ProjectCard.scss
=> fix #1775: Card view issue when Project status is selected as completed

src/components/LinksMenu/LinksMenu.jsx, src/projects/detail/containers/ProjectInfoContainer.js
Manager is able create a link without joining the project
=> Issue #1724 Manager is able create a link without joining the project

src/projects/create/components/ProjectOutline.js
=> fix #1742: Customer: Project estimate is not updated accordingly

src/components/User/UserWithName.scss, src/projects/list/components/Projects/ProjectManagerAvatars.jsx
=> fix #1798: Clicking user profile from tooltip also opens the project

src/api/projectAttachments.js
=> fix #1716: Not able to download files after editing the file name

src/components/MessageDetails/MessageDetails.jsx
=> fix issue 1772

src/components/RichTextArea/RichTextArea.scss
=> fix #1809: Reply not working sometimes

src/routes/notifications/constants/notifications.js, src/routes/settings/routes/notifications/components/NotificationSettingsForm.jsx, src/routes/settings/services/settings.js
#1740 
Also for this issue:
https://github.com/topcoder-platform/tc-project-service/pull/69
=> Issue 1740: No notification triggered for active status

src/projects/list/components/Projects/ProjectCardBody.jsx, src/projects/list/components/Projects/ProjectsGridView.jsx
https://github.com/appirio-tech/connect-app/issues/1750
=> Issue 1750: Disabled changing project status when project completed

src/api/projects.js
https://github.com/appirio-tech/connect-app/issues/1726
=> Issue 1726: Error 500 when searching for &

src/components/Select/Select.scss
=> Issue #1789 - should be able to remove single filter option

src/routes/notifications/components/NotificationsToolBar.jsx, src/routes/settings/routes.jsx
Fixes https://github.com/appirio-tech/connect-app/issues/1783
=> Update title from Profile and Settings to Notification Settings

src/components/TopBar/ProjectsToolBar.js
=> fix #1763 #1752: Project status filter disapper

src/projects/list/components/Projects/ProjectsGridView.scss
=> Issue #1762 - UI issue on Project page

src/projects/detail/Dashboard.scss
=> fix #1708: Tooltip inside project dashboard is cropped by the sidebar

src/components/ProjectStatus/editableProjectStatus.js
fix #1735, fix #1727, fix #1714, fix #1805
=> fix #1805fix #1735, fix #1727, fix #1714: Error 500 shows first before loading projects list

src/projects/detail/components/ProjectSpecSidebar.jsx
=> fix #1732, fix #1733: blue ticks shown even if they are not filled on specification page

src/components/TopBar/TopBarContainer.js
=> fix #1719: Filter is shown when we log in and log out

src/components/TeamManagement/TeamManagement.jsx
=> fix #1748: User section gets disabled when we leave it idle for a while

src/projects/detail/components/ProjectSpecSidebar.jsx, src/projects/reducers/project.js
=> fix #1794: Chat bot specification checkbox group selection question bug

src/projects/list/components/Projects/ProjectsCardView.jsx
=> fix issue_1788

src/projects/detail/components/SpecScreens.jsx, src/projects/detail/components/SpecSection.jsx
=> fix #1796: Issue with Wireframe project adding number of screens

src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx, src/components/TopBar/ProjectToolBar.js, src/components/TopBar/ProjectsToolBar.js, src/components/TopBar/TopBarContainer.scss
=> fix #1695: Navigation is jumping when loading Connect

src/components/RichTextArea/RichTextArea.jsx
PR for #1766 
update, please check.
=> Issue 1766

src/projects/detail/components/VisualDesignProjectEstimateSection.jsx
fyi @mtwomey @RishiRajSahu @vic-topcoder 
Not merging this in dev as dev already contains the same changes under some other commit.
=> Patching for error in loading specification tab for https://connect.topcoder.com/projects/1218/specification

src/config/projectQuestions/performance_testing.v1.0.js, src/config/projectWizard/index.js
Performance testing product is enabled with this change. https://github.com/appirio-tech/connect-app/issues/1911
=> Updated QA Intake Form - Performance Testing#1911

src/config/projectWizard/index.js
=> changed SFDC QA submenu description

src/routes/notifications/helpers/notifications.js
fix issue #1980 - Fix sorting for notifications
=> fix issue #1980 - Fix sorting for notifications

package-lock.json, src/components/BtnGroup/BtnGroup.jsx, src/components/BtnGroup/BtnGroup.scss, src/config/constants.js, src/routes/settings/components/SettingsPanel.scss, src/routes/settings/routes/notifications/components/NotificationSettingsForm.jsx, src/routes/settings/routes/notifications/components/NotificationSettingsForm.scss, src/routes/settings/routes/notifications/containers/NotificationSettingsContainer.jsx, src/routes/settings/services/settings.js
issue #1991 - Email settings
has to be deployed together with https://github.com/topcoder-platform/tc-notifications/pull/46 as API of notifications were changed
=> issue #1991 - Email settings

src/config/projectQuestions/enterprise_mobile.v1.0.js
@vikasrohit @vic-topcoder latest enterprise mobile form for dev
=> updated latest

src/projects/detail/components/SpecSection.jsx
Added icons mapping for QA types
=> Added icons mapping for QA types

src/config/constants.js, src/projects/actions/project.js, src/projects/actions/projectDashboard.js, src/projects/detail/components/PhaseCard/PhaseCard.jsx, src/projects/detail/components/ProjectPlanProgress.jsx, src/projects/detail/components/ProjectStage.jsx, src/projects/detail/components/ProjectStages.jsx, src/projects/detail/containers/ProjectPlanContainer.jsx
Phases Status and Price Data Fix
=> Phases Status and Price Data Fix

src/config/constants.js, src/projects/detail/ProjectDetail.jsx, src/projects/detail/components/PhaseCard/EditStageForm.jsx, src/projects/detail/components/PhaseCard/PhaseCard.jsx, src/projects/detail/components/ProjectPlanProgress.jsx, src/projects/detail/components/ProjectStage.jsx, src/projects/detail/components/ProjectStages.jsx, src/projects/detail/containers/ProjectPlanContainer.jsx
Showing progress/budget using the edited phase values
=> Showing progress/budget using the edited phase values

src/projects/detail/components/PhaseCard/PhaseCard.jsx
=> fix for mil 53 #2043

src/projects/detail/components/PhaseCardListFooter/PhaseCardListFooter.scss, src/projects/detail/components/ProjectProgress/ProjectProgress.jsx, src/projects/detail/components/ProjectProgress/ProjectProgress.scss
=> fix for mil 53 #2042

src/components/ActionCard/Comment.jsx, src/components/ActionCard/CommentMobile.jsx, src/components/Feed/FeedComments.jsx, src/components/Feed/FeedMobile.jsx, src/components/MessageDetails/MessageDetails.jsx, src/config/constants.js
=> fix for mil 53 #2040

src/components/ActionCard/Comment.jsx, src/components/ActionCard/CommentMobile.jsx
@gondzo @RishiRajSahu  
i think this should do it ...for both desktop and mobile
=> fixes post card formatting, both desktop and mobile #2034

src/components/ActionCard/ActionCard.scss
=> fix edit icon in old discussions tab #2059

src/helpers/format.js, src/projects/detail/components/ProjectPlanProgress.jsx
=> formatting of $ amount displayed #2069

src/components/MessageDetails/MessageDetails.jsx, src/components/MessageList/MessageList.jsx
=> fixed post formatting in discussions tab

src/components/GenericMenu/GenericMenu.scss, src/projects/detail/components/PhaseCard/PhaseCard.scss
=> correct phase card header background and other styles #2036

src/projects/detail/components/ProjectLayout.jsx, src/projects/detail/components/ProjectLayout.scss, src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/ProjectPlanContainer.jsx, src/projects/detail/containers/ScopeAndSpecificationContainer.jsx
=> project details secondary toolbar fixed at top on desktop #2064

src/components/ActionCard/CommentMobile.jsx, src/components/ActionCard/CommentMobile.scss, src/components/Feed/FeedComments.jsx, src/config/constants.js
=> Mil 53 issue 2039

src/projects/detail/components/PhaseCard/PhaseCard.jsx, src/projects/detail/components/ProjectStage.jsx
=> hide phase edit button for completed/cancelled projects/phases #2085

src/projects/detail/components/TwoColsLayout/TwoColsLayout.scss
@gondzo  
i am not entirely sure but i think the issue is caused due to using Sticky and is resolved by adding a non-zero z-index to the parent component
=> fixes User tooltip under text #2105

src/components/ProjectInfo/ProjectInfo.jsx
This is the same patch, which was applied to prod hotfix. For details see, https://github.com/appirio-tech/connect-app/pull/2169
=> fix freezing project dashboard page on mobile resolutions

src/components/Feed/NewPost.jsx, src/components/RichTextArea/RichTextArea.jsx, src/projects/detail/containers/FeedContainer.js
issue #2158 - Toggle text area placeholder for New post thread expanded & collapsed.
=> issue #2158 - Toggle text area placeholder for New post thread expanded & collapsed.

src/projects/reducers/project.js
This PR fixes mutation of the redux state for UPDATE_PHASE_SUCCESS reducer.
This PR is a part of fix for https://github.com/appirio-tech/connect-app/issues/2189, the second item.
After this PR is merged with `dev` branch I can merge `dev` branch into `feature/dashboard-improvements` and fix the first item of the issue #2189.
=> issue #2189 - item 2 - fixed mutating state for UPDATE_PHASE_SUCCESS reducer

src/api/messages.js
Reading messages from database after incorporation of elastic search in message api.
=> Patch release for breaking changes in message api

src/projects/detail/containers/ProjectPlanContainer.jsx
draft phases were visible to managers only, made them visible to superUsers also
=> HotFix - Made draft phases visible to superUsers also.

src/components/Feed/FeedComments.jsx
Fixed bug in calculating year for post.
=> Fixed bug in calculating year of posts

src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/ProjectInfoContainer.js, src/projects/detail/containers/ProjectPlanContainer.jsx
— Fixed missing links, of product attachments, in the left panel
=> Github issue#2204, Attachments/File Upload for phase specification question is not working

src/projects/detail/components/EditProjectForm/EditProjectForm.jsx
=> Fix #2184 make specification read only when project is active or delivered

src/projects/detail/components/ProjectProgress/ProjectProgress.scss
=> Fixes #2122 Fix progress bar 100% styling bug

src/projects/detail/ProjectDetail.jsx
=> #1946 Reroute copilot errors to page 403

src/config/constants.js, src/projects/actions/project.js, src/projects/detail/components/PhaseCard/EditStageForm.jsx, src/projects/reducers/project.js
=> #2086 Fix issue user alert for dirty phases

src/projects/detail/components/PhaseCard/EditStageForm.jsx
End date will be updated to the date when it is marked as delivered.
=> issue_2187 ffixed update end date when marked as delivered

src/projects/detail/components/PhaseCard/PhaseCard.jsx, src/projects/detail/containers/ProjectPlanContainer.jsx, src/projects/routes.jsx
To fix issues https://github.com/appirio-tech/connect-app/issues/2270 and https://github.com/appirio-tech/connect-app/issues/2269 I've removed routing for phases as was discussed here https://github.com/appirio-tech/connect-app/issues/2268#issuecomment-410659889
=> issue #2270 - Removed routing for phases

src/projects/detail/components/timeline/Milestone/Milestone.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx
issue #2267 - Change text for delivery milestone's dialog's content (button, title and description)
=> issue #2267 - Change text for delivery milestone's dialog's content

src/components/Feed/FeedComments.scss
=> Github issue#2310, *High Priority* Formatting in Messaging (CSS Issue)

src/components/ActionCard/Comment.scss, src/components/Feed/FeedComments.scss
one more try to fix the issue. Previous fix was causing date of the post to be hidden behind the header
=> Post overflow fix - take 2

src/projects/detail/components/timeline/WinnerSelectionBar/WinnerSelectionBar.jsx, src/projects/detail/components/timeline/WinnerSelectionBar/WinnerSelectionBar.scss
issue #2359 - Final designs - on winner selection UI is breaking
=> Issue 2359 - Final designs - on winner selection UI is breaking

src/components/ActionCard/Comment.scss
issue #2365 - Menu popup for a post is not completely visible
=> issue #2365 - Menu popup for a post is not completely visible

src/projects/actions/productsTimelines.js, src/projects/actions/project.js, src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx
issue #2364 - Complete/Delivery milestone is not marked as completed after clicking complete
=> issue #2364 - Complete/Delivery milestone is not marked as completed after clicking complete

src/projects/detail/containers/ProjectInfoContainer.js
issue #2374 - Progress bar at the sidebar is not dynamically updating on changes in timeline/milestones
=> issue #2374 - Progress bar at the sidebar is not dynamically updating on changes in timeline/milestones

src/projects/actions/productsTimelines.js, src/projects/detail/components/timeline/Milestone/Milestone.jsx
issue #2361 - Two types of `checkpoint-review` and `final-designs` milestones
=> issue #2361 - Two types of `checkpoint-review` and `final-designs` milestones

config/constants/dev.js, config/constants/master.js, config/constants/qa.js
trying enablement of maintenance mode by env variable again
=> Added missing variables

src/projects/actions/project.js
One possible fix for wrong difference between first and second milestone on activating a phase
=> Patch for inconsistent milestone start date for second milestone

src/projects/create/containers/CreateContainer.jsx
=> Patching the issue with project creation in logged out flow

src/projects/actions/project.js
fixed bug during calculation of change in startDate of a phase.
=> Hotfix/phase update bug fix[DEV]

src/components/RichTextArea/RichTextArea.jsx
Please see description here -> https://github.com/appirio-tech/connect-app/issues/2311
- Display spell check errors for post composer
=> Issue #2311: System spell check is not working with post composer

src/projects/detail/components/timeline/Timeline/Timeline.jsx, src/projects/detail/containers/ProductTimelineContainer.jsx
=> Fix for issue 2422

src/projects/actions/project.js, src/projects/actions/projectDashboard.js, src/projects/create/components/ProjectTypeCard.scss, src/projects/create/components/SelectProductTemplate.jsx, src/projects/create/components/SelectProductTemplate.scss, src/projects/detail/containers/ProjectAddPhaseContainer.jsx
Category names at design is left aligned but cards are centre aligned. So I keep both centre aligned. See the screenshot:
=> issues-2139: Support categories

src/projects/actions/project.js
fixed bug on dashboard when updating active phase.
=> fixed bug on dashboard when updating active phase.

src/helpers/projectHelper.js
=> Issue 2488

src/projects/detail/containers/ProjectPlanContainer.jsx
=> Fix issue 2419

src/projects/detail/components/timeline/LinkItem/LinkItem.scss, src/projects/detail/components/timeline/WinnerSelectionBar/WinnerSelectionBar.scss
=> issues_2482 Align design links correctly for design related milestones

src/components/RichTextArea/RichTextArea.jsx, src/components/RichTextArea/RichTextArea.scss
=> #2480 - Align user avatar in the post composer correctly

src/projects/detail/components/timeline/WinnerSelectionBar/WinnerSelectionBar.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeFinalDesigns/MilestoneTypeFinalDesigns.jsx
@maxceem  
removed some "not needed anymore because of this fix" code from WinnerSelectionBar.jsx
=> fixed #2490

src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx
=> fix issue #2466

config/constants/dev.js, config/constants/master.js, config/constants/qa.js
Updating segment key for #2475
=> updated key for segment analytics

src/components/Layout/Layout.jsx
i am not sure if it will fix main issue but it won't definitely show more than one alert message  at a time
=> attempting to fix #2091

src/projects/actions/productsTimelines.js, src/projects/detail/components/timeline/Milestone/Milestone.jsx, src/projects/detail/components/timeline/MilestoneExtensionRequest/MilestoneExtensionRequest.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeCheckpointReview/MilestoneTypeCheckpointReview.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeFinalDesigns/MilestoneTypeFinalDesigns.jsx
=> issues-2471: Adding field `details.metadata.waitingForCustomer`

package-lock.json, src/components/LinksMenu/LinksMenu.jsx, src/projects/detail/components/ProjectStage.jsx, src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/ProjectInfoContainer.js, src/projects/detail/containers/ProjectPlanContainer.jsx, src/projects/reducers/projectTopics.js
issue #2465 - Discussions not displaying on Dashboard sidebar
=> issue #2465 - Discussions not displaying on Dashboard sidebar

src/routes/settings/routes/notifications/components/NotificationSettingsForm.scss
Issue #2522 f2f - fix cutting last dropdown
=> Issue #2522 f2f - fix cutting last dropdown

.circleci/config.yml, package.json
updated react components branch
=> Updated react components branch

src/components/App/App.scss, src/index.jsx, src/styles/main.scss
fix Roboto font loading https://github.com/appirio-tech/connect-app/issues/2588
- Note: I've removed default font-size and line-height from body as for a long time we've been writing styles without these default styles, and putting them back breaks some styles
=> fix Roboto font loading

src/components/TopBar/Filters.js, src/components/TopBar/ProjectsToolBar.js, src/projects/create/components/SelectProductTemplate.jsx, src/projects/create/containers/CreateContainer.jsx, src/projects/detail/containers/ProjectAddPhaseContainer.jsx, src/reducers/templates.js
=> issue_2524 Add productCategories, projectCategories -> projectTypes

src/helpers/tcHelpers.js
issue #2576 - Restore Coder the Bot avatar
=> issue #2576 - Restore Coder the Bot avatar

src/helpers/milestoneHelper.js, src/projects/detail/components/timeline/MilestoneDelayNotification/MilestoneDelayNotification.jsx, src/projects/detail/components/timeline/MilestoneDelayNotification/MilestoneDelayNotification.scss, src/projects/detail/components/timeline/MilestoneDelayNotification/index.js, src/projects/detail/components/timeline/milestones/MilestoneTypeAddLinks/MilestoneTypeAddLinks.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeCheckpointReview/MilestoneTypeCheckpointReview.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeFinalDesigns/MilestoneTypeFinalDesigns.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeFinalFixes/MilestoneTypeFinalFixes.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypePhaseSpecification/MilestoneTypePhaseSpecification.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeProgress/MilestoneTypeProgress.jsx
For verifying, you may directly use these links. You may also need to set your system time to a future date after creating the project to verify this functionality. 
Final Design: http://local.topcoder-dev.com:3000/projects/7325 > 01. Rug iteration
Delivery (same page) > 02. visual design
Checkpoint review:http://local.topcoder-dev.com:3000/projects/7319 > 01. Visual Design
Phase spec: http://local.topcoder-dev.com:3000/projects/7409 > 01. Frontend Dev
Final Fixes: http://local.topcoder-dev.com:3000/projects/7379 > 02. Final fixes
=> add delay bar. fixes #2553

src/components/TopBar/ProjectToolBar.js, src/projects/components/projectsCard/ProjectCardBody.jsx, src/projects/components/projectsCard/ProjectCardHeader.jsx, src/projects/detail/components/SpecQuestions.jsx, src/projects/detail/components/SpecSection.jsx, src/projects/list/components/Projects/ProjectsGridView.jsx
=> issue_2518 Fix Jumbled/Incorrect Words Appearing in Projects

src/projects/detail/components/PhaseCard/EditStageForm.scss
=> issues_2454 Edit phase Form for smaller screen sizes

src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx
=> issue_2492 Allow editing link for final deliverable

src/components/LinksMenu/LinksMenu.jsx, src/projects/detail/components/SpecSection.jsx, src/projects/detail/containers/ProjectInfoContainer.js
Fixed bug: keeping phase-topic names in sync with phase name.
=> fixed bug updating left panel topic name

src/routes/notifications/containers/NotificationsContainer.jsx
issue #2637 - When we click notifications on Notifications page they are not marked as seen
=> issue #2637 - When we click notifications on Notifications page they are not marked as seen

src/helpers/projectHelper.js
issue #2642 - Invalid progress data in left panel
Logic now looks pretty clean and we summed up with our approach for duration calculation, so hopefully this time it would be our last fix for this :-)
=> issue #2642 - Invalid progress data in left panel

src/routes/settings/routes/notifications/components/NotificationSettingsForm.jsx, src/routes/settings/routes/notifications/components/NotificationSettingsForm.scss, src/routes/settings/routes/notifications/containers/NotificationSettingsContainer.jsx
issue #2641 - Enable web notification settings for copilots/managers
=> issue #2641 - Enable web notification settings for copilots/managers

src/components/Feed/NewPostMobile.scss, src/components/Home/Home.scss, src/components/LinksMenu/LinksMenu.scss, src/components/Modal/Modal.scss, src/components/PanelProject/PanelProject.scss, src/components/Select/Select.scss, src/components/TeamManagement/TeamManagement.scss, src/components/TopBar/ProjectsToolBar.scss, src/projects/components/projectsCard/ProjectCardHeader.scss, src/projects/create/components/ProjectSubmitted.scss, src/projects/detail/ProjectDetail.scss, src/projects/detail/components/EditProjectForm/EditProjectForm.scss, src/projects/detail/components/FeatureSelector/FeaturePicker.scss, src/projects/detail/components/ProjectSpecSidebar.scss, src/projects/detail/components/ReviewProjectButton/ReviewProjectButton.scss, src/projects/detail/components/SpecSection.scss, src/projects/detail/components/timeline/Milestone/Milestone.scss, src/projects/detail/components/timeline/TimelineHeader/TimelineHeader.scss, src/projects/detail/components/timeline/milestones/MilestoneTypeAddLinks/MilestoneTypeAddLinks.scss, src/projects/detail/components/timeline/milestones/MilestoneTypeCheckpointReview/MilestoneTypeCheckpointReview.scss, src/projects/detail/components/timeline/milestones/MilestoneTypeFinalDesigns/MilestoneTypeFinalDesigns.scss, src/projects/list/components/Projects/ProjectsGridView.scss, src/projects/list/components/ProjectsToolBar/ProjectsToolBar.scss, src/projects/list/components/Walkthrough/Walkthrough.scss, src/routes/settings/components/SettingsPanel.scss, src/styles/_variables.scss, src/styles/vendors/s-alert-default.scss
issue #2532 - New color variables in Connect App
=> Issue 2632 color variables

src/projects/detail/components/timeline/milestones/MilestoneTypeAddLinks/MilestoneTypeAddLinks.jsx
Fixed issue https://github.com/appirio-tech/connect-app/issues/2662 which is a duplicate of issue https://github.com/appirio-tech/connect-app/issues/2430
Note, that there was a long discussion whether it's an issue or feature https://github.com/appirio-tech/connect-app/issues/2430
=> issue #2662, #2430 - In add-links milestone, link value is not cleared when adding the next link

src/routes/settings/helpers/settings.js
We will revert these changes once we have merged dev to prod.
fyi @vikasrohit @maxceem
=> Using customer_info trait for pushing to prod as we don't have accounts app and member services changes pushed to PROD

src/routes/settings/helpers/settings.js, src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
-Enabled all address fields
-Setting country field for basic_info only if not present, we never override basic_info country
fyi @vikasrohit
=> [PROD]Hotfix/enabling remaining address fields

src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
also make it accept more phone formats
=> [HOTFIX] [PROD] fix phone validation to require country code

src/projects/detail/components/PostsRefreshPrompt/PostsRefreshPrompt.jsx
— Patch to disable the auto refresh, will fix it properly later
=> Github issue#2680, Dashboard is auto refreshing in every minute

src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
also make it accept more phone formats
=> [HOTFIX] [DEV] fix phone validation to require country code

src/components/TopBar/ProjectToolBar.js, src/projects/detail/ProjectDetail.jsx, src/projects/routes.jsx
[HOTFIX] [DEV] for issue #2683 - show proper error message when error happens during project loading
This PR also includes other hotfix to prod https://github.com/appirio-tech/connect-app/pull/2682
=> [HOTFIX] [DEV] for issue #2683 - show proper error message when error happens during project loading 

src/components/TopBar/ProjectToolBar.js, src/projects/detail/ProjectDetail.jsx, src/projects/routes.jsx
[HOTFIX] [PROD] for issue #2683 - show proper error message when error happens during project loading
=> [HOTFIX] [PROD] for issue #2683 - show proper error message when error happens during project loading

.circleci/config.yml, src/config/constants.js, src/projects/detail/components/SpecQuestionList/SpecQuestionList.jsx, src/projects/detail/components/SpecSection.jsx, src/projects/detail/components/SpecSection.scss
Added code to support BusinessUnit and CostCentre along with ref-code https://github.com/appirio-tech/connect-app/issues/2688
fyi @vikasrohit
=> [DEV]Added new section type for Zurich project intake forms

.circleci/config.yml, package-lock.json, src/components/TopBar/ProjectsToolBar.js
Handling absolute URLs correctly
=> [HOTFIX]Handling absolute links in Connect correctly

.circleci/config.yml, package-lock.json, src/components/TopBar/ProjectsToolBar.js
Handling absolute URLs correctly
=> [DEV]Hotfix/correcting aboslute urls ref

src/projects/detail/components/SpecSection.jsx
Minor correction in place holder name
=> Minor correction in place holder name

src/projects/detail/containers/ProjectInfoContainer.js
Disabled file upload based on presence of file template subsection
=> Allowing upload of files only if files subSection is present in template

src/projects/detail/containers/ProjectInfoContainer.js
Reverts appirio-tech/connect-app#2722
@RishiRajSahu reverting for now as it seems to cause issues with old projects. It is not able to find the appropriate template. We will debug it tomorrow.
=> Revert "Allowing upload of files only if files subSection is present in template"

src/projects/detail/containers/ProjectInfoContainer.js
Reverts appirio-tech/connect-app#2723
=> Revert "Hotfix/disable file upload for non managers cs"

src/components/TeamManagement/ProjectManagementDialog.js, src/components/TeamManagement/TopcoderManagementDialog.js
=> Enabled invite text field for admins always

.circleci/config.yml, src/config/constants.js, src/config/projectWizard/index.js, src/helpers/dependentQuestionsHelper.js, src/helpers/dependentQuestionsHelper.spec.js, src/helpers/wizardHelper.js, src/projects/create/components/FillProjectDetails.js, src/projects/create/components/FillProjectDetails.scss, src/projects/create/components/ProjectBasicDetailsForm.js, src/projects/create/components/ProjectWizard.jsx, src/projects/create/containers/CreateContainer.jsx, src/projects/detail/ProjectDetail.jsx, src/projects/detail/components/AddonOptions/AddonOptions.jsx, src/projects/detail/components/EditProjectForm/EditProjectForm.jsx, src/projects/detail/components/ProjectEstimationSection/ProjectEstimationSection.jsx, src/projects/detail/components/ProjectStage.jsx, src/projects/detail/components/ProjectStages.jsx, src/projects/detail/components/SpecQuestionList/SpecQuestionList.jsx, src/projects/detail/components/SpecQuestionList/SpecQuestionList.scss, src/projects/detail/components/SpecQuestions.jsx, src/projects/detail/components/SpecSection.jsx, src/projects/detail/components/SpecSection.scss, src/projects/detail/containers/ProjectPlanContainer.jsx, src/projects/detail/containers/ScopeAndSpecificationContainer.jsx, src/projects/detail/containers/ScopeContainer.jsx, src/projects/reducers/project.js
=> Dependent Questions features

src/projects/list/components/Projects/Projects.jsx, src/projects/list/components/Projects/ProjectsGridView.jsx
#2545 
Show blue bar aside project in the project list (grid view) when it has any unread notifcations.
=> Fix for issue 2545

src/projects/detail/components/timeline/Form/Form.jsx, src/projects/detail/components/timeline/Milestone/Milestone.jsx
https://github.com/appirio-tech/connect-app/issues/2555
=> Disable update milestone button if no changes.

src/routes/metadata/components/TemplateForm.jsx
#2771 
Fix saving value of "disabled" and "hidden" checkboxes in metadata management tool.
=> Fix for issue 2771

src/components/NotificationsDropdown/EnhancedDropdown.jsx, src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx
=> fixed issue #2750

src/routes/notifications/actions/index.js
#2623 
Remove showing this message in Connect App, show only in browser console
=> Fix for issue 2623

src/components/NotificationsDropdown/EnhancedDropdown.jsx, src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx
Reverts appirio-tech/connect-app#2778
=> Revert "fixed issue #2750"

src/components/Footer/Footer.jsx, src/components/FooterV2/FooterV2.jsx, src/components/TopBar/TopBarContainer.js
@mtwomey here i a pull request to close #2787 and #2786
=> Hot fix/footers

src/reducers/members.js
https://github.com/appirio-tech/connect-app/issues/2772
=> Load current user as members.

src/actions/loadUser.js, src/api/groups.js, src/api/orgConfig.js, src/components/Grid/GridView.jsx, src/components/TopBar/NewProjectNavLink.jsx, src/components/TopBar/ProjectToolBar.js, src/components/TopBar/ProjectsToolBar.js, src/config/constants.js, src/projects/components/projectsCard/NewProjectCard.jsx, src/projects/components/projectsCard/ProjectsCardView.jsx, src/projects/list/components/Projects/Projects.jsx, src/projects/list/components/Projects/ProjectsGridView.jsx, src/reducers/loadUser.js
This is the PR with a winning submission for the challenge https://www.topcoder.com/challenges/30081357
The full functionality requires [PR](https://github.com/topcoder-platform/tc-project-service/pull/242) to the project service to be merged.
But this PR can be safely merged independently, as nothing would be broken and only networks errors to non-existent endpoints would be logged in browser console.
=> winning submission from challenge 30081357 - Topcoder Connect - Organization configs

src/components/TeamManagement/ProjectManagementDialog.js, src/components/TeamManagement/TeamManagement.jsx, src/components/TeamManagement/TopcoderManagementDialog.js, src/components/User/UserTooltip.jsx, src/components/User/UserTooltip.scss
winning submission for F2F challenge 30083314 - Topcoder Connect - Team Management - List members
Fix for issue https://github.com/appirio-tech/connect-app/issues/2743#issuecomment-462018444
=> Team Management - List invited members on the sidebar

src/components/ProjectStatus/ProjectStatusChangeConfirmation.jsx
=> Update cancellation reasons

src/components/FileList/AddFilePermissions.jsx, src/components/FileList/FileListItem.jsx, src/components/LinksMenu/EditFileAttachment.jsx, src/components/UserAutoComplete/UserAutoComplete.jsx, src/projects/create/components/FillProjectDetails.js
fix https://github.com/appirio-tech/connect-app/issues/2883
=> [PROD] Hotfix/chxoosing attachment members

src/components/TeamManagement/TopcoderManagementDialog.js
=> Issue in adding user by handle in some cases.

src/projects/detail/components/PhaseCard/PhaseCard.jsx, src/projects/detail/components/ProjectStage.jsx
Enabling copilots/managers who are project member to edit the phase.
fyi @vikasrohit
=> [MASTER]Hotfix/enable copilots to edit phasecard

src/components/ProjectInfo/ProjectInfo.jsx, src/projects/list/components/Projects/ProjectsGridView.jsx
Reverts appirio-tech/connect-app#2908
sorry @Gunasekar-K incorrectly merged the hotfix to your branch
=> Revert "Hotfix/unable to activate v2 projects"

src/projects/detail/components/ProjectStage.jsx, src/projects/detail/components/timeline/Milestone/Milestone.jsx, src/projects/detail/components/timeline/Timeline/Timeline.jsx
fyi @vikasrohit https://github.com/appirio-tech/connect-app/issues/2917
=> [HOTFIX-Master]Fixed copilots access for milestones. GitIssue#2917

src/projects/detail/components/ProjectStage.jsx, src/projects/detail/components/timeline/Milestone/Milestone.jsx, src/projects/detail/components/timeline/Timeline/Timeline.jsx
https://github.com/appirio-tech/connect-app/issues/2917
=> [HOTFIX-Dev]Hotfix/copilot access check fixes

src/projects/detail/containers/TeamManagementContainer.jsx
fyi @RishiRajSahu @maxceem @RiteshTC
=> Github issue#2922, Error message for inviting users by email, in topcoder team, is not visible

src/config/projectWizard/index.js
=> Added support for QA forms and refactored project estimate helper methods

src/helpers/dependentQuestionsHelper.js, src/helpers/dependentQuestionsHelper.spec.js
=> added support for boolean literal when evaluating conditions.

src/api/templates.js, src/projects/detail/components/SpecQuestions.jsx, src/routes/metadata/components/MetaDataPanel.jsx
Feature/add ons flag
This PR requires merging Project Service supporting PR first https://github.com/topcoder-platform/tc-project-service/pull/293
=> Add-ons flag

src/projects/detail/components/PhaseCard/PhaseCard.jsx, src/projects/detail/components/ProjectStage.jsx, src/projects/detail/components/ProjectStageTabs/ProjectStageTabs.jsx, src/projects/detail/components/timeline/Timeline/Timeline.jsx, src/routes/notifications/constants/notifications.js
issue #2455 - red cue for Timeline and Specification tabs
=> Red cue for Timeline and Specification tabs

src/components/LinksMenu/LinksMenu.jsx, src/components/LinksMenu/LinksMenuAccordion.jsx, src/components/LinksMenu/LinksMenuAccordion.scss, src/projects/detail/containers/ProjectInfoContainer.js
Winning submission from challenge 30088832 - Topcoder Connect - List post links on the sidebar
part of the fix for issue #2937
=> List post links on the sidebar

src/components/Feed/FeedComments.scss
fix for full screen mode of thread
=> move textarea to the top in the fullscreen post mode

src/components/Feed/FeedComments.jsx, src/projects/detail/containers/FeedContainer.js, src/routes.jsx
Fix so we can do various actions with private topics properly.
=> [PROD] Hotfix/fix private topics

src/components/Feed/FeedComments.jsx, src/projects/detail/containers/FeedContainer.js, src/routes.jsx
Reverts appirio-tech/connect-app#2987
=> Revert "[PROD] Hotfix/fix private topics"

src/projects/actions/loadProjects.js, src/projects/list/components/Projects/Projects.jsx, src/projects/reducers/projectSearch.js
=> Bypassed 'Walkthrough' page when customer non-zero count of non-active projects

src/components/Feed/Feed.jsx, src/components/RichTextArea/RichTextArea.jsx, src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/SingleFeedContainer.jsx
Found quite good and quick fix for issue https://github.com/appirio-tech/connect-app/issues/2185 regarding slow typing in the topics, which could be applied as a hotfix.
So far I've created a hotfix against DEV branch. If you think it worth and safe to apply to PROD, I'll create another one.
The main intention with a hotfix is to get feedback if the solution is fast and comfortable enough or should we make bigger changes to speed up typing more.
See [comment](https://github.com/appirio-tech/connect-app/issues/2185#issuecomment-487540174) for details.
=> [DEV] Hotfix/topics rerenders

src/components/RichTextArea/RichTextArea.jsx
On deleting an attachment:
- update post button becomes active.
-  able to delete attachments now.
=> fix issue #3017

src/config/projectWizard/index.js, src/projects/create/containers/CreateContainer.jsx
This is client side-part of the task to store project estimation on the server.
This PR should be only merged AFTER we deploy respective changes at the server which are handled by the next challenge https://www.topcoder.com/challenges/30091706.
=> send project estimation during project creation to the server

src/projects/reducers/project.js
Hotfix for issue `Hide 403 error page when a user accepts the invite` https://github.com/appirio-tech/connect-app/issues/3040
Tested locally, works good.
=> [PROD] [Hotfix] Hide 403 error page when a user accepts the invite

src/projects/reducers/project.js
Hotfix for DEV branch related to PROD hotfix PR https://github.com/appirio-tech/connect-app/pull/3044
=> [DEV] [Hotfix] Hide 403 error page when a user accepts the invite 

src/config/projectWizard/index.js
For the issue https://github.com/appirio-tech/connect-app/issues/3057
=> support buildingBlocks with a price as an expression

src/projects/detail/containers/ProjectAddPhaseContainer.jsx
In case we release new app and qa forms to prod
=> Hiding adding from add phase catalog

src/config/projectWizard/index.js
=> Trying to handle formula in the price field of the building block

src/components/RichTextArea/LinkPlugin/LinkPlugin.js, src/components/RichTextArea/LinkPlugin/utils/handlePaste.js
@vikasrohit DEV hotfix related to https://github.com/appirio-tech/connect-app/pull/3086
=> [HOTFIX][DEV] DraftJs Link Fix

src/helpers/templates.js, src/projects/detail/ProjectDetail.jsx
=> Github issue#3097, Project does not load when project plan (phases) is empty

src/routes/metadata/components/MetaDataPanel.jsx
issue #3103 - winning submission from challenge 30093251 - Topcoder Connect - Metadata - Fix create and duplicate issues
Tested locally, after this fix creating/duplicating of all templates in the Metadata work good.
=> [Metadata Management] New project template action is not working

src/components/RichTextArea/RichTextArea.jsx
fix for https://github.com/appirio-tech/connect-app/issues/3114
=> [HOTFIX/MASTER]-added check for undefined attachments

src/components/RichTextArea/RichTextArea.jsx
fix for - https://github.com/appirio-tech/connect-app/issues/3114
=> [HOTFIX/DEV]-added check for undefined attachments

src/components/TeamManagement/TeamManagement.scss
=> fix team layout issues #3156

src/components/TeamManagement/ProjectManagementDialog.js, src/components/TeamManagement/TeamManagement.scss
fix layout both topcoder and customer team
=> fix layout both topcoder and customer team

src/projects/detail/components/Accordion/Accordion.jsx, src/projects/detail/components/SpecQuestionList/SpecQuestionList.scss, src/projects/detail/components/SpecQuestions.jsx
Make Connect forms to support new slider component #3169
=> Make Connect forms to support new slider component #3169

src/helpers/wizardHelper.js
Do not merge yet, hotfix is merged into dev for testing and if all goes well and if things are blocked in production, then only we would merge this Hotfix to the master.
=> [Do NOT Merge] Hotfix/support multiple questions with same field name

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
fix: filter skills inside SkillsQuestion component ignoring case of skill categories which come from skill API
=> [HOTFIX] [PROD] Filter skills ignore case of categories

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
fix: filter skills inside SkillsQuestion component ignoring case of skill categories which come from skill API
=> [HOTFIX] [DEV] Filter skills ignore case of categories

src/projects/actions/project.js
Fix for #3189 
fyi @RishiRajSahu @maxceem
=> Github issue#3189, Unable to activate a phase without explicitly setting start date to today's date

src/helpers/projectHelper.js, src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
Fix for making Messages tab visible for not so old projects.
A dirty fix for  NPE in draft-js library
fyi @maxceem
=> Hotfix/post release 2.4.13.5

src/helpers/utils.js, src/projects/detail/components/EditProjectForm/EditProjectForm.jsx, src/projects/reducers/project.js
=> Disable "Save Changes" button again if there is no changes.

src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/MessagesTabContainer.jsx, src/projects/reducers/projectTopics.js, src/projects/routes.jsx
Dev version of the hotfix https://github.com/appirio-tech/connect-app/pull/3204
=> [DEV] Hotfix/post release 2.4.13.6

src/helpers/milestoneHelper.js
- Should fix it.
fyi @maxceem @RishiRajSahu
=> Github issue#3202, Progress bar is showing wrong progress for Final fix milestone

src/helpers/markdownToState.js
Dev version of the hotfix https://github.com/appirio-tech/connect-app/pull/3217
=> [DEV] Hotfix/post release 2.4.13.7 (DEV)

src/api/users.js, src/config/constants.js, src/routes/settings/actions/index.js, src/routes/settings/routes/system/components/ChangeEmailForm.jsx
=> Enabled support for email-change vai connect for customers.

src/projects/create/components/FillProjectDetails.js, src/projects/create/components/HeaderWithProgress.js
=> [HOTFIX/MASTER]added support for hiding price in forms

src/projects/create/components/FillProjectDetails.js, src/projects/create/components/HeaderWithProgress.js
added support for hiding price in forms
=> [HOTFIX/DEV] support for hidding project price

src/api/projectSummary.js, src/helpers/format.js, src/helpers/projectHelper.js, src/projects/detail/components/ProjectSummaryReport/ProjectBudgetReport.jsx
=> Hide 'Reports' menu item.

src/routes/notifications/helpers/notifications.js
=> adding temporary condition to avoid old notifications missing

src/api/challenges.js, src/api/works.js, src/config/constants.js, src/helpers/challenges.js, src/helpers/workstreams.js, src/projects/actions/works.js, src/projects/detail/components/workstreams/AddWorkItem.jsx, src/projects/detail/components/workstreams/AddWorkItem.scss, src/projects/detail/components/workstreams/DeletePopup.jsx, src/projects/detail/components/workstreams/DeletePopup.scss, src/projects/detail/components/workstreams/WorkItemList.jsx, src/projects/detail/components/workstreams/WorkItemList.scss, src/projects/detail/components/workstreams/WorkView.jsx, src/projects/detail/components/workstreams/WorkView.scss, src/projects/detail/components/workstreams/WorkViewEdit.jsx, src/projects/detail/containers/AddWorkItemContrainer.jsx, src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/WorkItemsContainer.jsx, src/projects/detail/containers/WorkItemsContainer.scss, src/projects/reducers/works.js, src/reducers/alerts.js, src/styles/mixins/_typography.scss
=> Code 30098703

src/routes/notifications/helpers/notifications.js
Reverts appirio-tech/connect-app#3265
=> Revert "adding temporary condition to avoid old notifications missing"

src/assets/icons/icon-star-solid.svg, src/assets/icons/icon-star.svg, src/components/RichTextArea/RichTextArea.jsx, src/components/RichTextEditable/RichTextEditable.jsx, src/components/RichTextEditable/RichTextEditable.scss, src/projects/actions/workTimelines.js, src/projects/create/components/HelpModal.jsx, src/projects/detail/components/work-timeline/CompleteMilestoneButtonContainer.jsx, src/projects/detail/components/work-timeline/WorkTimelineMilestoneReview/GeneralFeedback.jsx, src/projects/detail/components/work-timeline/WorkTimelineMilestoneReview/GeneralFeedback.scss, src/projects/detail/components/work-timeline/WorkTimelineMilestoneReview/IndividualFeedbackRow.jsx, src/projects/detail/components/work-timeline/WorkTimelineMilestoneReview/IndividualFeedbackRow.scss, src/projects/detail/components/work-timeline/WorkTimelineMilestoneReview/WorkTimelineMilestoneReview.jsx, src/projects/detail/components/work-timeline/WorkTimelineMilestoneReview/WorkTimelineMilestoneReview.scss, src/projects/detail/components/workstreams/ActiveMilestoneSummary.jsx, src/projects/detail/components/workstreams/WorkList.jsx, src/projects/detail/components/workstreams/WorkListCard.jsx, src/projects/detail/components/workstreams/WorkView.jsx, src/projects/detail/components/workstreams/Workstreams.jsx, src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/WorkTimelineMilestoneReviewContainer.jsx, src/projects/detail/containers/WorkTimelineMilestoneReviewContainer.scss, src/projects/detail/containers/WorkViewContainer.jsx, src/projects/detail/containers/WorkstreamsContainer.jsx, src/projects/reducers/workTimelines.js, src/projects/routes.jsx
Topcoder Connect - Works - Review
=> Topcoder Connect - Works - Review

src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx, src/routes/settings/routes/profile/components/ProfileSettingsForm.scss
Fix alerts for Country selection and business phone in Profile settings
=> fix for #3263

src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx, src/routes/settings/routes/profile/components/ProfileSettingsForm.scss
=> (fix for issue #3263) hide country selection alert on outside click in

src/components/ActionCard/Comment.jsx, src/components/Feed/FeedComments.jsx, src/components/Feed/NewPost.jsx, src/components/MessageDetails/MessageDetails.jsx, src/components/Posts/PostsContainer.jsx, src/components/RichTextArea/RichTextArea.jsx, src/components/TeamManagement/ProjectManagementDialog.js, src/components/TeamManagement/TeamManagement.jsx, src/components/TeamManagement/TopcoderManagementDialog.js, src/components/TopBar/TopBarContainer.js, src/components/TopicCard/TopicCard.jsx, src/components/User/UserTooltip.jsx, src/components/User/UserWithName.jsx, src/components/UserSummary/UserSummary.jsx, src/helpers/tcHelpers.js, src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/FeedContainer.js, src/projects/detail/containers/MessagesContainer.js, src/projects/list/components/Projects/ProjectsGridView.jsx
— Gracefully handling the missing first and last name in the _search endpoint of member api
=> Github issue#3289, Use handle instead of first and last name for creating avatars in Connect

config/constants/dev.js, config/constants/master.js, config/constants/qa.js, src/components/Feed/NewPostMobile.jsx, src/components/FileList/AddFiles.jsx, src/components/LinksMenu/FileLinksMenu.jsx, src/components/RichTextArea/RichTextArea.jsx, src/config/constants.js, src/projects/detail/containers/AssetsInfoContainer.jsx
-- Restricted the file upload extensions
=> Confluence#SEC-10 - File upload for connect

src/components/MenuItem/MenuItem.jsx, src/components/MenuItem/MenuItem.scss, src/components/MenuList/MenuList.jsx, src/components/UserSidebar/UserSidebar.jsx, src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx, src/routes/settings/routes/profile/components/ProfileSettingsForm.scss, src/routes/settings/routes/profile/containers/ProfileSettingsContainer.jsx
Fixes for these issues:
https://github.com/appirio-tech/connect-app/issues/3278
https://github.com/appirio-tech/connect-app/issues/3277
=> fix profile page and registration page issues

src/components/NotificationBadge/NotificationBadge.scss, src/projects/detail/containers/ProjectInfoContainer.js, src/projects/list/components/Projects/ProjectsGridView.jsx, src/routes/notifications/helpers/notifications.js
Need red cue for new file or link uploaded for the project #3274
=> Need red cue for new file or link uploaded for the project #3274

src/components/MobilePage/MobilePage.scss, src/components/TopicDrawer/TopicDrawer.jsx, src/components/TopicDrawer/TopicDrawer.scss
=> Messaging on mobile #3213

src/components/ProjectInfo/ProjectInfo.jsx, src/components/ProjectInfo/ProjectInfo.scss, src/projects/list/components/Projects/ProjectsGridView.jsx, src/projects/list/components/Projects/ProjectsGridView.scss
Fix UI for REF on the project details page #3212
=> Fix UI for REF on the project details page: Issue #3212

src/components/TeamManagement/AutocompleteInputContainer.jsx
…team #3225
403 in suggesting users to the Customers while adding members to the team #3225
=> 403 in suggesting users to the Customers: Issue #3225

src/components/TeamManagement/TeamManagement.jsx
Fixes issue: https://github.com/appirio-tech/connect-app/issues/3294
Account: pshah_customer
Account: pshah_manager
=> fixes: [Issue #3294]remove manage button and rename invite people button

src/routes/metadata/components/MetaDataPanel.jsx, src/routes/metadata/components/MetaDataPanel.scss, src/routes/metadata/containers/FormDetails.jsx, src/routes/metadata/containers/MetaDataContainer.scss, src/routes/metadata/containers/MilestoneTemplateDetails.jsx, src/routes/metadata/containers/PlanConfigDetails.jsx, src/routes/metadata/containers/PriceConfigDetails.jsx, src/routes/metadata/containers/ProductCategoryDetails.jsx, src/routes/metadata/containers/ProductTemplateDetails.jsx, src/routes/metadata/containers/ProjectTemplateDetails.jsx, src/routes/metadata/containers/ProjectTypeDetails.jsx
keep entered data if error occurs during entity updating #3179
=> Eeep entered data if error occurs during entity updating Issues #3179

src/components/AssetsLibrary/FilesGridView.jsx, src/components/AssetsLibrary/SubFolder.jsx, src/components/FileIcon.jsx, src/components/MobilePage/MobilePage.scss, src/config/projectWizard/index.js, src/projects/actions/projectMember.js
This PR will contain the post release fixes. I think we can wait at least a day before merging it while collecting fixes. For example there are few PRs from Bug Bash may got ready soon.
The list of fixes (may be updated):
- Fix for issue https://github.com/appirio-tech/connect-app/issues/3211. It has been fixed during CF19 but has been reverted in `cf19` branch accidentally.
=> [HOTFIX] [PROD] Post-release 2.4.15.1

src/components/TeamManagement/TeamManagement.scss, src/config/constants.js, src/helpers/utils.js, src/projects/actions/projectMember.js, src/projects/components/projectsCard/ProjectCard.jsx, src/projects/components/projectsCard/ProjectCard.scss, src/projects/components/projectsCard/ProjectsCardView.jsx, src/projects/detail/ProjectDetail.jsx, src/projects/list/components/Projects/Projects.jsx, src/projects/list/components/Projects/ProjectsGridView.jsx, src/projects/reducers/project.js, src/projects/reducers/projectSearch.js
This PR will contain the post-release fixes part 2. I think we can wait at least a day before merging it while collecting fixes. 
The list of fixes (**updated**):
- Fix for issue [P3: Update Invited Registered User Workflow](https://github.com/appirio-tech/connect-app/issues/3311). 
- Fix for issue [P3: Update Invited Unregistered 'Join Project' Workflow](https://github.com/appirio-tech/connect-app/issues/3310) which is not ready yet.
- Fix for issue [Handles are not cleared after successful invites](https://github.com/appirio-tech/connect-app/issues/3155)
=> [HOTFIX] [PROD] Post-release 2.4.15.2

docs/LocalSetup.md, src/api/projectAttachments.js, src/api/projectMemberInvites.js, src/api/projectMembers.js, src/api/projectReports.js, src/api/projects.js, src/api/templates.js, src/api/timelines.js, src/reducers/alerts.js
=> upgrade project api to v5

src/api/templates.js, src/reducers/templates.js, src/routes/metadata/components/MetaDataPanel.jsx
Topcoder Connect - Avoid unnecessary requests
=> Topcoder Connect - Avoid unnecessary requests

src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
Fix issue: https://github.com/appirio-tech/connect-app/issues/3359
=> add timezone input in profile settings page

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
Implementation for issue https://github.com/appirio-tech/connect-app/issues/3369
=> [PROD] [HOTFIX] support Skills questions showing all skills without filtering by categories 

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
Implementation for issue https://github.com/appirio-tech/connect-app/issues/3369
=> [DEV] [HOTFIX] support Skills questions showing all skills without filtering by categories

src/projects/reducers/project.js
Fix for issue https://github.com/appirio-tech/connect-app/issues/3386 in DEV
NOTE: that issue above on DEV could be slightly different than reported above. On PROD/DEV it shows Join Project dialog for some moment, but after it hides it and performs approve/decline action successfully.
After the fix, the Join Project dialog is not shown anymore.
=> [HOTFIX] [DEV] fix: approve/decline copilot 

src/components/TeamManagement/MemberItem.jsx, src/components/TeamManagement/MemberItem.scss, src/components/TeamManagement/TeamManagement.jsx, src/components/TeamManagement/TeamManagement.scss, src/components/TeamManagement/TopcoderManagementDialog.js, src/components/User/UserTooltip.jsx, src/components/User/UserTooltip.scss, src/projects/detail/containers/TeamManagementContainer.jsx
[challenge](https://www.topcoder.com/challenges/30109902)
=> Project Team - Update UI

src/components/Sticky.jsx, src/components/TeamManagement/TeamManagement.jsx, src/projects/detail/containers/DashboardContainer.jsx
=> fix sticky issue

src/components/TeamManagement/TeamManagement.jsx, src/routes/settings/helpers/settings.js
https://github.com/appirio-tech/connect-app/issues/3397
https://github.com/appirio-tech/connect-app/issues/3446
=> [HOTIFX] [PROD] fix country code error for numeric code

src/projects/detail/components/SpecQuestions.jsx
Should hide the estimator by template configuration
=> [Prod] Hotfix/hiding pricing estimator

src/projects/detail/components/SpecQuestions.jsx
Should hide the estimator by template configuration
=> [Dev] Hotfix/hiding pricing estimator

src/helpers/markdownToState.js
- Renders nested code block as inline block except in case of list item it renders code as fence.
- In case of multiple paragraph inside list item, only the last one was being considered.
Fix this to consider all paragraph inside list item.
=> Fix: some lines disappearing during editing in editor based on Draftjs

src/projects/actions/loadProjects.js
don't requests user details about M2M users
=> [HOTFIX] [DEV] fix when updatedBy m2m

package-lock.json, package.json, src/components/TeamManagement/MemberItem.jsx
=> Fix local time calculation

src/projects/actions/loadProjects.js
don't requests user details about M2M users
=> [HOTFIX] [PROD] fix when updatedBy m2m

package-lock.json, package.json, src/components/TeamManagement/MemberItem.jsx
fyi @maxceem merging the changes to non-hotfix branch as we are not pushing it as hotfix.
=> Fix local timezone UTC cut-off

src/projects/reducers/project.js
Fix issue https://github.com/appirio-tech/connect-app/issues/3481
=> [HOTFIX] [DEV] members disappear

src/projects/reducers/project.js
=> [HOTFIX] [PROD] members disappear

package-lock.json, package.json, src/components/TeamManagement/MemberItem.jsx
=> Fix local timezone selection

src/routes/metadata/components/MetaDataPanel.jsx, src/routes/metadata/components/TemplateForm.jsx
[challenge](https://www.topcoder.com/challenges/30112454)
=> New Fields for Project Templates

src/api/projectMembers.js
=> Using handle lower member api

src/api/projectMembers.js
Should fix the issue with a particular copilot handle to be added to the team
=> Using handleLower filter instead of handle

src/components/UserSummary/UserSummary.scss, src/reducers/alerts.js
=> issue-3440-iversonLv Minor UI Issues

src/config/constants.js, src/routes/notifications/constants/notifications.js, src/routes/notifications/helpers/notifications.js, src/routes/notifications/services/notifications.js
=> fix issue-3375

package-lock.json, package.json, src/components/AssetsLibrary/FilesGridView.jsx, src/components/AssetsLibrary/FilterColHeader.jsx, src/components/AssetsLibrary/FilterColHeader.scss, src/components/AssetsLibrary/GridView.scss, src/components/AssetsLibrary/LinksGridView.jsx, src/components/AssetsLibrary/SubFolder.jsx, src/config/constants.js, src/config/store.js, src/projects/detail/containers/AssetsInfoContainer.jsx
=> Add assets list filter

src/components/TeamManagement/TeamManagement.jsx
Supporting fix for https://github.com/topcoder-platform/tc-project-service/issues/464
=> [HOTIFX] [DEV] [2.5.1] Remove invites by handle

src/components/TeamManagement/TeamManagement.jsx
Supporting fix for https://github.com/topcoder-platform/tc-project-service/issues/464
This PR should be merged and deployed BEFORE hotfix for Project Service https://github.com/topcoder-platform/tc-project-service/pull/466
=> [HOTIFX] [PROD] [2.5.1] Remove invites by handle

src/api/projectMembers.js
- Fix for https://github.com/appirio-tech/connect-app/issues/3732. Should be applied together with Project Service fix https://github.com/topcoder-platform/tc-project-service/pull/494 to avoid showing emails for non-admin users
=> [HOTIFX] [DEV] Patch release 2.7.1 - part 3 for DEV

src/projects/detail/containers/ProjectSummaryReportContainer.jsx, src/projects/reducers/projectReports.js
don't use random for report URL
=> [HOTIFX] [DEV] Patch release 2.7.1 - part 4 for DEV 

src/config/constants.js
Reduced the session expiration length by 5 minutes to show the modal 5 minutes before the actual session expiration.
=> Reduced the session expiration legnth

src/projects/actions/projectTopics.js
Fix https://github.com/appirio-tech/connect-app/issues/3765
=> [HOTIFX] [PROD] Post release 2.7.2

src/projects/create/components/StaticSection.scss
=> issues_3568 Common to all projects Title and Description UI issue

src/components/MenuItem/MenuItem.scss, src/projects/detail/components/PhaseCard/PhaseCard.scss
Reverts appirio-tech/connect-app#3763
=> Revert "Issue 3435 fix"

src/components/MenuItem/MenuItem.scss, src/projects/detail/components/PhaseCard/PhaseCard.scss
PR to the correct branch instead of https://github.com/appirio-tech/connect-app/pull/3763
=> Issue 3435

src/components/TeamManagement/MemberItem.jsx
Reverts appirio-tech/connect-app#3753
=> Revert "fix for issue-3733"

src/components/TeamManagement/MemberItem.jsx
PR to the correct branch instead of https://github.com/appirio-tech/connect-app/pull/3753
=> Issue 3733

src/helpers/stateToMarkdown.js
Reverts appirio-tech/connect-app#3760
=> Revert "Fix: remove character styling inside code block on save"

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
Reverts appirio-tech/connect-app#3762
=> Revert "issue 3634 fix"

src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx
PR to the correct branch instead of https://github.com/appirio-tech/connect-app/pull/3762
=> Issue 3634

src/helpers/stateToMarkdown.js
Reverts appirio-tech/connect-app#3796
=> Revert "Revert "Fix: remove character styling inside code block on save""

src/api/projectMemberInvites.js, src/components/TeamManagement/ProjectManagementDialog.js, src/components/TeamManagement/TopcoderManagementDialog.js, src/projects/actions/project.js, src/projects/actions/projectMember.js, src/projects/detail/ProjectDetail.jsx, src/projects/list/components/Projects/Projects.jsx, src/projects/reducers/project.js
Topcoder Connect - Update Invite Endpoints  
https://www.topcoder.com/challenges/30118162
Update connect-app client-side code to use updated tc-project-service invite endpoints.
=> Update Invite Endpoints

src/api/projectAttachments.js, src/components/AssetsLibrary/AddLink.jsx, src/components/AssetsLibrary/FilesGridView.jsx, src/components/AssetsLibrary/FilterColHeader.jsx, src/components/AssetsLibrary/GridView.scss, src/components/AssetsLibrary/LinksGridView.jsx, src/components/AssetsLibrary/SubFolder.jsx, src/components/FileList/AddFilePermissions.jsx, src/components/FileList/AddFilePermissions.scss, src/components/FileList/FileList.scss, src/components/FileList/FileListItem.jsx, src/components/LinksMenu/EditFileAttachment.jsx, src/components/LinksMenu/EditLinkModal.jsx, src/components/Select/FormsySelect.jsx, src/components/TagSelect/TagSelect.jsx, src/projects/actions/projectAttachment.js, src/projects/detail/components/FileListContainer.jsx, src/projects/detail/containers/AssetsInfoContainer.jsx, src/projects/reducers/project.js
Submission from Code Challenge (https://www.topcoder.com/challenges/30119190)
=> challenge-30119190-links-as-attachments

package-lock.json, package.json, src/projects/detail/components/SpecQuestions.jsx
This PR to support fix for https://github.com/appirio-tech/connect-app/issues/3557 which has been done in `react-components` repo https://github.com/appirio-tech/react-components/pull/351.
Though current PR fixes a wide range of errors it enables support for validators, which we define in Project Templates via `validations` property which was been disabled.
=> Fix custom validation rules

src/helpers/projectHelper.js, src/projects/actions/loadProjects.js
I'm not sure why this PR showing some changes except of https://github.com/appirio-tech/connect-app/pull/3818/files#diff-d56303a39aaee6a7f3747dcea5adca69L69. As all other changes seem to be already merged into DEV.
=> [HOTFIX] [DEV] Project listing when member service fails

src/projects/actions/loadProjects.js
=> [HOTFIX] [PROD] Project listing when member service fails

package-lock.json
#3823 Choose country code for phone using dropdown is broken
=> #3823 Choose country code for phone using dropdown is broken

src/components/FileDownload.jsx
Reverts appirio-tech/connect-app#3844
=> Revert "[HOTFIX] [DEV] Post release 2.8.1"

src/components/SelectDropdown/SelectDropdownBase.jsx, src/projects/detail/components/SkillsQuestion/SkillsQuestionBase.jsx, src/projects/detail/components/TalentPickerQuestion/TalentPickerQuestion.jsx
Winning submission of F2F challenge 30122011 - Topcoder Connect - Fix Performance Issue
=> fix performance issue in talent picker question

src/api/requestInterceptor.js
Remove timeout to avoid failing projects loading with a slow internet connection.
=> [HOTFIX] [PROD] Post release 2.8.1 

src/components/StatusFilters/StatusFilters.scss, src/components/StatusFilters/StatusFiltersList.jsx, src/components/StatusFilters/StatusFiltersMobile.jsx
PR for https://github.com/appirio-tech/connect-app/issues/3775
=> issues_3775 User is able to click on the tabs that are already selected.

src/routes/settings/routes/profile/components/ProfileSettingsForm.scss
=> Issue #3832 fixed

src/routes/settings/routes/profile/components/ProfileSettingsAvatar.jsx, src/routes/settings/routes/profile/components/ProfileSettingsAvatar.scss, src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx, src/routes/settings/routes/profile/containers/ProfileSettingsContainer.jsx
=> issues_3770 Profile Icon doesn’t display the default image in Avatar.

src/components/TeamManagement/TopcoderManagementDialog.js
observer role is removed from the team management modal
=> Observer role fixed

src/projects/detail/containers/ProjectAddPhaseContainer.scss
https://github.com/appirio-tech/connect-app/issues/3576
=> Hidden top bar buttons fix

src/routes/settings/routes/profile/components/ProfileSettingsForm.scss
Reverts appirio-tech/connect-app#3908
Wrong branch.
=> Revert "Issue #3832 fixed"

src/components/TeamManagement/TeamManagement.scss, src/components/User/UserTooltip.scss
issues_3842: showing ellipsis ... at the end
=> issues_3842: showing ellipsis ... at the end

src/projects/detail/components/SkillsQuestion/SkillsQuestionBase.jsx
select dropdown duplicate entry fixed
=> issue 3816 fixed

src/components/Select/Select.scss, src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
=> fix business phone validation and clipped text issue in country selection

src/components/SelectDropdown/SelectDropdownBase.jsx, src/routes/metadata/components/MetaDataPanel.jsx
- SelectDropdown support placeholder
- Don't show first option in dropdown when there is no value in all metadata editor drop-downs as it misleads
=> Support SelectDropdown placeholder & Fix Metadata default option

src/components/FAQ/FAQItem.jsx, src/components/FAQ/FAQItem.scss, src/config/constants.js
=> fixed issue with link type text's formatting.

src/components/Footer/Footer.jsx
=> Removed footer links which are not part of Connect FAQs git#issue4061

.circleci/config.yml, src/routes/faqs/components/FaqToolBar.jsx, src/routes/faqs/routes.jsx
=> Create Custom ToolBar for General FAQ page. 

src/helpers/projectHelper.js, src/helpers/templates.js, src/projects/detail/containers/ProjectInfoContainer.js
=> [Patch-Prod]Hotfix/added support to render project faq based on metadata

.circleci/config.yml, package-lock.json, src/projects/detail/components/Accordion/Accordion.jsx, src/projects/detail/components/SpecQuestionList/SpecQuestionList.scss, src/projects/detail/components/SpecQuestions.jsx, src/projects/detail/components/TalentPickerQuestion/TalentPickerQuestionV2.jsx, src/projects/detail/components/TalentPickerRow/TalentPickerRowV2.jsx, src/projects/detail/components/TalentPickerRow/TalentPickerRowV2.scss
Created new component for talent-picker with additional fields. ref - https://github.com/appirio-tech/connect-app/issues/4072
=> Support for new talent-picker component

.circleci/config.yml, src/config/constants.js
=> redirecting login/registration to global reg/login pages

src/routes/reports/components/ReportsToolBar.jsx, src/routes/reports/routes.jsx
=> fix: open reports tab after searching

src/components/IncomepleteUserProfileDialog/IncompleteUserProfileDialog.jsx, src/components/IncomepleteUserProfileDialog/IncompleteUserProfileDialog.scss, src/components/IncompleteUserProfile/IncompleteUserProfile.jsx, src/config/constants.js, src/helpers/tcHelpers.js, src/projects/create/components/FillProjectDetails.js, src/projects/create/components/UpdateUserInfo.js, src/projects/detail/ProjectDetail.jsx, src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
Includes all the issues related to progressive profile:
- [Profile Timezone Enhancement](https://github.com/appirio-tech/connect-app/issues/4109)
- [New Progressive Profile Completion Scenario: Opens a Project](https://github.com/appirio-tech/connect-app/issues/4105)
- [Evolve Progressive Profile Completion Dynamic Behavior](https://github.com/appirio-tech/connect-app/issues/4104)
=> Progressive profile improvements

src/components/FooterNeedHelp/FooterNeedHelp.jsx, src/components/FooterNeedHelp/FooterNeedHelp.scss, src/components/UserSidebar/UserSidebar.jsx, src/projects/detail/containers/ProjectInfoContainer.js
=> feat: "Give Application Feedback" link

src/components/TeamManagement/CopilotManagementDialog.js, src/components/TeamManagement/TeamManagement.jsx, src/components/TeamManagement/TeamManagement.scss, src/components/TeamManagement/TopcoderManagementDialog.js, src/config/permissions.js, src/projects/detail/containers/TeamManagementContainer.jsx
=> feat: separate invitation dialog for copilots

src/components/ActionCard/AddComment.jsx, src/components/Feed/Feed.jsx, src/components/Feed/FeedComments.jsx, src/projects/detail/containers/FeedContainer.js
=> fix: preserve new comment during feed reloading

src/components/TeamManagement/TeamManagement.jsx, src/components/TeamManagement/TeamManagement.scss, src/components/TeamManagement/TopcoderManagementDialog.js, src/projects/detail/containers/TeamManagementContainer.jsx
=> feat: remote "project role" selection

docs/permissions.html, src/config/constants.js, src/config/permissions.js, src/helpers/tcHelpers.js, src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx, src/routes/settings/routes/profile/containers/ProfileSettingsContainer.jsx
=> feat: Segment Profile Information by User Role

src/routes/settings/routes/profile/components/ProfileSettingsForm.jsx
=> fix: don't show warning without business phone

src/components/Footer/Footer.jsx
- [Connect home page not opening on mobile browser](https://github.com/appirio-tech/connect-app/issues/4137)
=> [HOTFIX] [PROD] Patch release 2.12.1

src/components/MenuItem/MenuItem.jsx, src/components/UserSidebar/UserSidebar.jsx, src/projects/detail/containers/ProjectInfoContainer.js
two minor changes:
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/ProjectInfoContainer.js#L452 Comment this line, we need to hide this option
- https://github.com/appirio-tech/connect-app/blob/40ea623df1ad5329217ebbd5c6fa9daf2e1ca3ff/src/components/UserSidebar/UserSidebar.jsx#L67
https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/ProjectInfoContainer.js#L599 
and these two should be hyperlink to https://forms.gle/hwRWYB3cGQnKVpjk7
=> [HOTFIX] [PROD] Patch release 2.12.2

src/components/MenuItem/MenuItem.jsx, src/components/UserSidebar/UserSidebar.jsx, src/projects/detail/containers/ProjectInfoContainer.js
two minor changes:
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/ProjectInfoContainer.js#L452 Comment this line, we need to hide this option
- https://github.com/appirio-tech/connect-app/blob/40ea623df1ad5329217ebbd5c6fa9daf2e1ca3ff/src/components/UserSidebar/UserSidebar.jsx#L67
https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/ProjectInfoContainer.js#L599 
and these two should be hyperlink to https://forms.gle/hwRWYB3cGQnKVpjk7
=> [HOTFIX] [DEV] Patch release 2.12.2

src/projects/detail/containers/ProjectAddPhaseContainer.jsx
This fix to avoid the issue with a delay of ES indexing after moving from RabbitMQ to Kafka in Project Service, see https://github.com/topcoder-platform/tc-project-service/issues/584#issuecomment-709286420.
=> feat: don't reload phases after adding

docs/permissions.html, src/components/TeamManagement/CopilotManagementDialog.js, src/components/TeamManagement/TeamManagement.jsx, src/config/permissions.js
=> feat: remove copilots

src/projects/actions/productsTimelines.js, src/projects/detail/components/timeline/Milestone/Milestone.jsx, src/projects/detail/components/timeline/Timeline/Timeline.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeDeliverableReview/MilestoneTypeDeliverableReview.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeDeliverableReview/MilestoneTypeDeliverableReview.scss, src/projects/detail/components/timeline/milestones/MilestoneTypeDeliverableReview/index.js, src/projects/detail/components/timeline/milestones/MilestoneTypeReporting/MilestoneTypeReporting.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeReporting/MilestoneTypeReporting.scss, src/projects/detail/components/timeline/milestones/MilestoneTypeReporting/index.js, src/projects/detail/containers/ProductTimelineContainer.jsx
- "Reporting" milestone type
- "Deliverable Review" milestone type
- "Final Deliverable Review" milestone type
- "Deliverable Final Fixes" milestone type
=> Add New Milestone Types

src/config/constants.js, src/projects/actions/productsTimelines.js, src/projects/detail/components/CreatePhaseForm/CreatePhaseForm.jsx, src/projects/detail/components/CreatePhaseForm/CreatePhaseForm.scss, src/projects/detail/components/CreatePhaseForm/index.js, src/projects/detail/components/PhaseCard/EditStageForm.jsx, src/projects/detail/components/timeline/Milestone/Milestone.jsx, src/projects/detail/components/timeline/Timeline/Timeline.jsx, src/projects/detail/components/timeline/createMilestoneForm/CreateMilestoneForm.jsx, src/projects/detail/components/timeline/createMilestoneForm/CreateMilestoneForm.scss, src/projects/detail/components/timeline/createMilestoneForm/index.js, src/projects/detail/containers/DashboardContainer.jsx, src/projects/detail/containers/ProductTimelineContainer.jsx, src/projects/reducers/productsTimelines.js, src/reducers/alerts.js
@maxceem  fixed some issue and add new **create milestone** form
=> fix: some issue and add milestone

src/config/constants.js, src/projects/actions/project.js, src/projects/detail/components/CreatePhaseForm/CreatePhaseForm.jsx, src/projects/detail/components/timeline/CreateMilestoneForm/CreateMilestoneForm.jsx, src/projects/detail/components/timeline/Milestone/Milestone.jsx, src/projects/detail/components/timeline/createMilestoneForm/CreateMilestoneForm.jsx, src/projects/detail/containers/DashboardContainer.jsx, src/projects/reducers/productsTimelines.js, src/projects/reducers/project.js, src/reducers/alerts.js
=> fix: fix additional issues

config/constants/dev.js, config/constants/master.js, config/constants/qa.js, src/config/constants.js, src/projects/actions/productsTimelines.js, src/projects/detail/components/timeline/milestones/MilestoneTypeCheckpointReview/MilestoneTypeCheckpointReview.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeDeliverableReview/MilestoneTypeDeliverableReview.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx, src/projects/detail/components/timeline/milestones/MilestoneTypeFinalDesigns/MilestoneTypeFinalDesigns.jsx, src/projects/detail/containers/DashboardContainer.jsx
=> fix: change milestone.type to const type

src/projects/create/components/ProjectSubmitted.jsx, src/projects/create/components/ProjectSubmitted.scss
=> fix: #4194

src/projects/detail/ProjectDetail.jsx
=> fix: show error when Project Template is not found

src/projects/list/components/Projects/Projects.jsx, src/projects/list/components/Projects/ProjectsGridView.scss
=> fix: #4234

src/projects/list/components/Projects/Projects.jsx, src/projects/reducers/projectSearch.js
@maxceem please review for #4236
=> fix: #4236

src/projects/detail/containers/ProjectInfoContainer.js, src/projects/detail/containers/ProjectInfoContainer.scss
@maxceem please review for #4234
=> fix: issue #4234 for detail page

src/projects/detail/components/JobPickerRow/JobPickerRow.jsx, src/projects/detail/components/JobPickerRow/JobPickerRow.scss, src/projects/detail/components/JobsPickerQuestion/JobsPickerQuestion.jsx, src/projects/detail/components/JobsPickerQuestion/JobsPickerQuestion.scss, src/projects/detail/components/SpecQuestions.jsx
=> fix: #4206

src/projects/create/components/ProjectSubmitted.jsx
@maxceem  please for review #4254
=> fix:issue #4254

src/projects/detail/components/JobsPickerQuestion/JobsPickerQuestion.jsx
@maxceem please review for #4206
=> fix:issue-4206

src/components/Feed/FeedComments.jsx, src/components/Feed/FeedComments.scss, src/helpers/markdownToState.js
Add error message when message could not be rendered.
=> Empty msg break

src/projects/detail/containers/ProjectInfoContainer.js
fix issue https://github.com/appirio-tech/connect-app/issues/4258
=> [HOTFIX] [DEV] v2 project cannot load

src/projects/detail/containers/ProjectInfoContainer.js
=> [HOTFIX] [PROD] v2 project cannot load

src/projects/detail/components/JobPickerRow/JobPickerRow.jsx, src/projects/detail/components/JobsPickerQuestion/JobsPickerQuestion.jsx
@maxceem  please review for #4206
=> fix: #4206 add trim()

src/projects/detail/components/JobsPickerQuestion/JobsPickerQuestion.jsx
@maxceem please review for #4206
=> fix: #4206 disblae next button when add empty job

src/projects/detail/components/JobPickerRow/JobPickerRow.jsx
=> fix: issue #4263 add validation

src/actions/loadUser.js, src/api/groups.js, src/config/constants.js, src/projects/detail/components/EditProjectDefaultsForm/EditProjectDefaultsForm.jsx, src/projects/detail/components/GroupsField/GroupsField.module.scss, src/projects/detail/components/GroupsField/index.js, src/projects/detail/components/NDAField/index.jsx
- Refactor NDAField implementation #4273 
- Add Groups Field https://github.com/appirio-tech/connect-app/issues/4270
=> Project Defaults, part 2

src/helpers/protectComponent.js, src/projects/detail/components/EditProjectDefaultsForm/EditProjectDefaultsForm.jsx
=> hide project defaults page for customer role

.circleci/config.yml, src/components/TuiEditor/TuiEditor.scss, src/components/TuiEditor/index.jsx, src/projects/detail/components/DescriptionField/DescriptionField.scss, src/projects/detail/components/DescriptionField/index.jsx
issue https://github.com/appirio-tech/connect-app/issues/4329
=> [DEV] [HOTFIX]fix links create in Job Description

config/constants/dev.js, config/constants/master.js, config/constants/qa.js, src/config/constants.js, src/projects/detail/components/BillingAccountField/index.js
=> fix: issue #4315

src/components/MobileMenu/MobileMenu.jsx, src/components/TopBar/TopBarContainer.js
=> fix: issue #4281

.circleci/config.yml, src/projects/detail/components/TaasProjectWelcome/TaasProjectWelcome.jsx, src/projects/detail/components/TaasProjectWelcome/TaasProjectWelcome.scss
=> Added description for TaaS redirection button

src/projects/detail/components/PhaseCard/PhaseCard.jsx
Fix this issue: [https://github.com/appirio-tech/connect-app/issues/4348](url)
=> Fix: hide actual phase status from customers

src/projects/detail/components/CreatePhaseForm/CreatePhaseForm.jsx, src/projects/detail/components/CreatePhaseForm/CreatePhaseForm.scss, src/projects/detail/components/PhaseCard/EditStageForm.jsx, src/projects/detail/components/PhaseCard/EditStageForm.scss
#4349 add subtext that reads: "255 character maximum" under the "Description" header
=> Add subtext 255 character maximum under the Description header

src/components/TeamManagement/TeamManagement.scss, src/projects/detail/components/timeline/CreateMilestoneForm/CreateMilestoneForm.jsx
Fix member row item should be vertically middle aligned #4360
=> Fix issue #4360

src/projects/detail/components/timeline/CreateMilestoneForm/CreateMilestoneForm.jsx
Fix cancel button in Add Milestone form #4362 
https://user-images.githubusercontent.com/65434125/117244825-f5935180-ae63-11eb-8784-619ad432e1dd.mp4
=> Fix issue #4362

.circleci/config.yml, src/components/TeamManagement/TeamManagement.jsx, src/components/TeamManagement/TeamManagement.scss, src/projects/detail/components/CreatePhaseForm/CreatePhaseForm.jsx, src/projects/detail/components/PhaseCard/EditStageForm.jsx, src/projects/detail/components/timeline/CreateMilestoneForm/CreateMilestoneForm.jsx
https://github.com/appirio-tech/connect-app/milestone/112
=> Bug fix release - 2.20.0

src/config/constants.js, src/projects/detail/components/JobPickerRow/JobPickerRow.jsx, src/projects/detail/components/JobsPickerQuestion/JobsPickerQuestion.jsx
=> [PROD][HOTFIX] restrict the duration field on Jobs to a 4 week minimum

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/containers/DashboardContainer.jsx
Post prod release fixes - https://github.com/appirio-tech/connect-app/issues/4432
https://github.com/appirio-tech/connect-app/issues/4428
=> [PROD][HOTFIX]Fix whitespace and Hide Milestones with Draft status from customer view

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/containers/DashboardContainer.jsx
Post prod release fixes - #4432
#4428
=> [DEV][HOTFIX]Fix whitespace and Hide Milestones with Draft status from customer view

src/projects/detail/components/SimplePlan/CreateSimplePlan/CreateSimplePlan.jsx, src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.jsx, src/projects/detail/containers/DashboardContainer.jsx
1. Exclude email from member copilots popup:
-- Fixed: 
--- hide email on copilot avatar
--- use phase.members data for rendering
2. When adding copilots, when clicking to save, it show copilot for a second then disappear, when refresh it will show it:
-- Backend issue
=> [new milestone concept] fix issue #4439

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.scss, src/projects/detail/components/SimplePlan/components/MilestoneChallengeFooter/MilestoneChallengeFooter.jsx, src/projects/detail/components/SimplePlan/components/MilestoneChallengeRow/MilestoneChallengeRow.scss
=> fix: issue about pagination and gap line

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx
=> fix: issue about milestone challenge count

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/components/SimplePlan/components/ConfirmMoveMilestoneDate/ConfirmMoveMilestoneDate.scss, src/projects/detail/components/SimplePlan/components/MilestoneHeaderRow/MilestoneHeaderRow.jsx, src/projects/detail/components/SimplePlan/components/MilestoneMoveDateButton/MilestoneMoveDateButton.scss, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.jsx, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.scss
=> fix: change table for customer view

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/components/SimplePlan/components/MilestoneHeaderRow/MilestoneHeaderRow.jsx, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.jsx
=> fix: hide checkbox when edit and new row

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/components/SimplePlan/components/AddCopilotsSidebar/AddCopilotsSidebar.jsx, src/projects/detail/components/SimplePlan/components/MilestoneChallengeFooter/MilestoneChallengeFooter.jsx, src/projects/detail/components/SimplePlan/components/MilestoneChallengeRow/MilestoneChallengeRow.jsx, src/projects/detail/components/SimplePlan/components/MilestoneDeleteButton/MilestoneDeleteButton.jsx, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.jsx, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.scss
Fixes for issues
- #4460 
- #4427 
- #4415 - open WM for challenges, and open it in new tab/window
=> [HOTFIX][PROD]Fixes for issues 4427, 4460 and 4415

src/projects/detail/components/SimplePlan/ManageMilestones/ManageMilestones.jsx, src/projects/detail/components/SimplePlan/components/AddCopilotsSidebar/AddCopilotsSidebar.jsx, src/projects/detail/components/SimplePlan/components/MilestoneChallengeFooter/MilestoneChallengeFooter.jsx, src/projects/detail/components/SimplePlan/components/MilestoneChallengeRow/MilestoneChallengeRow.jsx, src/projects/detail/components/SimplePlan/components/MilestoneDeleteButton/MilestoneDeleteButton.jsx, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.jsx, src/projects/detail/components/SimplePlan/components/MilestoneRow/MilestoneRow.scss
Fixes for issues
- #4460 
- #4427 
- #4415 - open WM for challenges, and open it in new tab/window
=> [HOTFIX][DEV] Fixes for issues 4427, 4460 and 4415

src/config/constants.js, src/projects/detail/components/SimplePlan/components/AddCopilotsSidebar/AddCopilotsSidebar.jsx, src/projects/detail/components/SimplePlan/components/MilestonesApprovalNotification/MilestonesApprovalNotification.jsx
- Fixed this comment https://github.com/appirio-tech/connect-app/issues/4484#issuecomment-914903658 
- Renamed Phased to Paused
=> [HOTFIX][PROD] Hotfix/milestone message rewording

src/config/constants.js, src/projects/detail/components/SimplePlan/components/AddCopilotsSidebar/AddCopilotsSidebar.jsx, src/projects/detail/components/SimplePlan/components/MilestonesApprovalNotification/MilestonesApprovalNotification.jsx
- Fixed this comment https://github.com/appirio-tech/connect-app/issues/4484#issuecomment-914903658
- Renamed paused to phased (not merged to dev)
=> [HOTFIX][DEV] Hotfix/milestone message rewording

.eslintignore, src/projects/detail/components/SimplePlan/components/MilestoneApprovalButton/MilestoneApprovalButton.jsx, src/projects/detail/components/SimplePlan/components/MilestonesApprovalNotification/MilestonesApprovalNotification.jsx, src/projects/detail/components/SimplePlan/components/MilestonesApprovalNotification/MilestonesApprovalNotification.scss
- Rewording of approved milestones message
- Listing milestones in expandable modal
=> [HOTFIX][PROD] Milestone Approval Additional Fixes

src/projects/detail/containers/DashboardContainer.jsx
Fixed bug in adding new milestone with null copilots
=> [HOTFIX][DEV] Fixed bug in adding new milestone with null copilots

connect-automation/page-objects/common-page/common.helper.ts, connect-automation/page-objects/login/login.po.ts, connect-automation/page-objects/profile-update/my-profile/my-profile.helper.ts, connect-automation/page-objects/project-creation-flow/projects/projects.helper.ts, connect-automation/page-objects/project-creation-flow/projects/projects.po.ts, connect-automation/page-objects/project-milestone/project-milestone.helper.ts, connect-automation/page-objects/project-milestone/project-milestone.po.ts, connect-automation/page-objects/project-settings/project-settings.helper.ts, connect-automation/test-suites/project-creation-flow/projects.spec.ts, connect-automation/test-suites/project-settings-flow/project-settings.spec.ts
Topcoder Connect - E2E Test Automation - Random tests fail
=> Fixes for Challenge: 

src/components/UserSidebar/UserSidebar.jsx
https://topcoder.atlassian.net/browse/MP-294
=> Remove navigation for profile and account details from Connect

src/helpers/utils.js
https://topcoder.atlassian.net/browse/PS-196
=> PROD - hotfix for PS-196
